/**
 * generate-docs.ts
 *
 * Reads all data/*.json files and produces 10 markdown documents + README.
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import type {
  FigmaComponent,
  VariantAxis,
  TokenCategory,
  GapAnalysis,
  Section,
  FunctionalCategory,
  Taxonomy,
} from './types.js';

const __dirname = fileURLToPath(new URL('.', import.meta.url));
const ROOT = join(__dirname, '..');

function ensureDir(p: string) {
  if (!existsSync(p)) mkdirSync(p, { recursive: true });
}

function writeDoc(p: string, content: string) {
  ensureDir(dirname(p));
  writeFileSync(p, content, 'utf-8');
  console.log(`  wrote ${p.replace(ROOT, '.')}`);
}

function readJson<T>(name: string): T {
  return JSON.parse(readFileSync(join(ROOT, 'data', name), 'utf-8')) as T;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

const SECTION_LABELS: Record<Section, string> = {
  atoms: 'Atoms',
  molecules: 'Molecules',
  inputs: 'Inputs & Forms',
  other: 'Other',
};

const CATEGORY_LABELS: Record<FunctionalCategory, string> = {
  actions: 'Actions',
  navigation: 'Navigation',
  'data-entry': 'Data Entry',
  'data-display': 'Data Display',
  feedback: 'Feedback & Overlays',
  'content-layout': 'Content Layout',
  product: 'Product',
  selection: 'Selection & Controls',
};

// Color swatch using placehold.co image (renders on GitHub as a real colored square)
function colorSwatch(hex: string): string {
  const clean = hex.replace(/^#/, '').toLowerCase();
  return `![](https://placehold.co/12x12/${clean}/${clean}.png)`;
}

function matchStatus(figmaKey: string, gapColors: GapAnalysis['colors']): string {
  if (gapColors.matched.some((e) => e.figmaKey === figmaKey)) return '✅ Matched';
  if (gapColors.figmaOnly.some((e) => e.figmaKey === figmaKey)) return '⚠️ Figma-only';
  return '—';
}

// Detect auto-generated Figma state names
function isInconsistentStateName(val: string): boolean {
  return /^state\d+$/i.test(val) || /^variant\d+$/i.test(val) || /^property\s*\d+$/i.test(val);
}

// Values that appear in the State axis but are NOT interaction states
const NON_STATE_BREAKPOINTS = new Set(['Desktop', 'Tablet', 'Mobile']);
const NON_STATE_INPUT_TYPES = new Set(['Checkbox', 'Radio']);
const STATE_TYPOS: Record<string, string> = {
  'Focu': 'Focus',
  'Disable': 'Disabled',
  'Maxium': 'Maximum',
  'Focused': 'Focus (duplicate of "Focus")',
};

function classifyStateValue(val: string): 'valid' | 'breakpoint' | 'inputType' | 'typo' | 'autoGenerated' | 'nonStandard' {
  if (isInconsistentStateName(val)) return 'autoGenerated';
  if (NON_STATE_BREAKPOINTS.has(val)) return 'breakpoint';
  if (NON_STATE_INPUT_TYPES.has(val)) return 'inputType';
  if (STATE_TYPOS[val]) return 'typo';
  return 'valid';
}

// ---------------------------------------------------------------------------
// Dependency map (atom/molecule composition)
// ---------------------------------------------------------------------------

const DEPENDENCY_MAP: Record<string, string[]> = {
  'Button group': ['Button', 'Text Button—Icon Right'],
  'Toast Bar': ['Close Button'],
  'Text Section with Button Group': ['Button', 'Text Button—Icon Right'],
  'Free Trial Card': ['Button', 'Stepper CTA'],
  'Product Content': ['Button', 'Stepper CTA', 'Reviews', 'Badges and Tags', 'Price and Label'],
  'Slider page selector': ['Next-Previous Selector', 'Slider Scroll Bar'],
  'Carousel Product': ['Next-Previous Buttons', 'Slider Scroll Bar', 'Slider page selector'],
  'Section Headline with CTA': ['Button', 'Text Button—Icon Right'],
  'Section Headline': [],
  'Text Section': [],
  'Basic Form': ['Text Input (single line)', 'Dropdown', 'Checkbox', 'Radio Button', 'Button'],
  'Multi-CTA List': ['CTA Row'],
  'Product Grid Card': ['Button', 'Badges and Tags', 'Price and Label', 'Reviews'],
  'Modal Dialog': ['Button', 'Close Button', 'Modal Button Group'],
  'Product Lineup—Single': ['Button', 'Stepper CTA', 'Reviews', 'Badges and Tags', 'Price and Label'],
  'Subnav Dropdown': ['Subnav Dropdown Options'],
  'Button': [],
  'Text Button—Icon Right': [],
  'Text Button—Icon Left': [],
  'Close Button': [],
  'Next-Previous Buttons': [],
  'Expand-Collapse Button': [],
  'Increase-Decrease Buttons': [],
  'Floating Action Button': [],
  'Floating Action Button with Text': [],
  'Play Button': [],
  'Breadcrumbs': [],
  'Simple Menu': [],
  'Button Menu': [],
  'Tabbed Selector': ['Tabbed Selector Button'],
  'Accordion Section': ['Expand-Collapse Button'],
  'Modal Button Group': ['Button'],
  'CTA Row': ['Button'],
  'Category Button': [],
  'Stepper CTA': ['Increase-Decrease Buttons', 'Button'],
  'Stepper Control': ['Increase-Decrease Buttons'],
  'Reviews': ['Star'],
  'Stateful Action Button': ['Button'],
};

function buildDependencyWeight(): Map<string, number> {
  const counts = new Map<string, number>();
  for (const deps of Object.values(DEPENDENCY_MAP)) {
    for (const dep of deps) {
      counts.set(dep, (counts.get(dep) ?? 0) + 1);
    }
  }
  return counts;
}

// ---------------------------------------------------------------------------
// Algorithmic consolidation detection
// ---------------------------------------------------------------------------

interface ConsolidationCandidate {
  compA: string;
  compB: string;
  reason: string;
}

function detectConsolidationCandidates(components: FigmaComponent[]): ConsolidationCandidate[] {
  const candidates: ConsolidationCandidate[] = [];
  const seen = new Set<string>();

  for (let i = 0; i < components.length; i++) {
    for (let j = i + 1; j < components.length; j++) {
      const a = components[i];
      const b = components[j];
      const pairKey = `${a.name}|${b.name}`;
      if (seen.has(pairKey)) continue;
      seen.add(pairKey);

      // Exact duplicate names
      if (a.name === b.name) {
        candidates.push({
          compA: `${a.name} (Figma ID: ${a.figmaId})`,
          compB: `${b.name} (Figma ID: ${b.figmaId})`,
          reason: 'Duplicate frame name — deduplicate in Figma',
        });
        continue;
      }

      const aAxes = Object.keys(a.properties);
      const bAxes = Object.keys(b.properties);
      const aAxeSet = new Set(aAxes);
      const sharedAxes = bAxes.filter((ax) => aAxeSet.has(ax));

      // Identical property axis sets (same axes, different names)
      if (
        sharedAxes.length >= 2 &&
        sharedAxes.length === aAxes.length &&
        sharedAxes.length === bAxes.length &&
        a.functionalCategory === b.functionalCategory
      ) {
        candidates.push({
          compA: a.name,
          compB: b.name,
          reason: `Same property axes [${sharedAxes.join(', ')}] and functional category — consider merging`,
        });
        continue;
      }

      // Common name stem (first meaningful word, length > 4)
      const aStem = a.name.split(/[\s—\-(]/)[0];
      const bStem = b.name.split(/[\s—\-(]/)[0];
      if (
        aStem === bStem &&
        aStem.length > 4 &&
        aStem !== 'Product' && // Product* components are intentionally separate
        aStem !== 'Section'
      ) {
        candidates.push({
          compA: a.name,
          compB: b.name,
          reason: `Common name stem "${aStem}" — review whether these could share a single component with variant props`,
        });
      }
    }
  }

  return candidates;
}

// ---------------------------------------------------------------------------
// Doc 01: Token Map (swatches fixed, Layout split into Font Sizes + Grid)
// ---------------------------------------------------------------------------

function doc01TokenMap(tokens: TokenCategory, gap: GapAnalysis): string {
  const lines: string[] = [
    '# 01 · Design Token Map',
    '',
    '> Generated from Figma Variables (`raw/figma-variables.json`).',
    '> DTCG tiers: **P** = Primitive · **S** = Semantic · **C** = Component.',
    '> Code match: ✅ matched in `commerce-theme` · ⚠️ Figma-only (needs code implementation) · — no data.',
    '',
  ];

  // Colors
  lines.push('## Colors', '');
  lines.push('| | Figma Name | Hex | Group | DTCG | Code Match | Code Key |');
  lines.push('|--|------------|-----|-------|------|------------|----------|');
  for (const t of tokens.colors) {
    const swatch = colorSwatch(t.rawValue);
    const matchEntry = gap.colors.matched.find((e) => e.figmaKey === t.figmaKey);
    const matchStr = matchEntry ? '✅ Matched' : gap.colors.figmaOnly.some((e) => e.figmaKey === t.figmaKey) ? '⚠️ Figma-only' : '—';
    const codeKey = matchEntry?.codeKey ?? '—';
    const tier = /primary|secondary|deep colors|bright/i.test(t.figmaKey) ? 'P' : 'S';
    lines.push(`| ${swatch} | \`${t.figmaKey}\` | \`${t.rawValue.toLowerCase()}\` | ${t.group} | ${tier} | ${matchStr} | \`${codeKey}\` |`);
  }

  if (gap.colors.codeOnly.length > 0) {
    lines.push('', '### Colors in `commerce-theme` not referenced in Figma', '');
    lines.push('These exist in code but have no matching Figma variable. Candidates for removal or addition to Figma.', '');
    lines.push('| | Code Key | Hex |');
    lines.push('|--|----------|-----|');
    for (const e of gap.colors.codeOnly) {
      const swatch = colorSwatch(e.codeValue ?? '#000');
      lines.push(`| ${swatch} | \`${e.codeKey}\` | \`${e.codeValue}\` |`);
    }
  }

  // Typography
  lines.push('', '## Typography', '');
  lines.push('| Figma Name | Family | Weight | Line Height | Letter Spacing | Group |');
  lines.push('|------------|--------|--------|-------------|----------------|-------|');
  for (const t of tokens.typography) {
    const m = t.rawValue.match(/family:\s*"([^"]+)".*weight:\s*(\d+).*lineHeight:\s*([^,]+),.*letterSpacing:\s*([^)]+)/);
    if (m) {
      lines.push(`| \`${t.figmaKey}\` | ${m[1]} | ${m[2]} | ${m[3].trim()} | ${m[4].trim()} | ${t.group} |`);
    }
  }

  // Font Sizes (separated from layout)
  if (tokens.fontSizes.length > 0) {
    lines.push('', '## Font Size References', '');
    lines.push('> These are numeric size values referenced by the typography composite tokens above.', '');
    lines.push('| Figma Name | Size (px) | Referenced By | Code Match |');
    lines.push('|------------|-----------|---------------|------------|');
    for (const t of tokens.fontSizes) {
      const typoRef = tokens.typography.find((ty) => ty.rawValue.includes(t.figmaKey));
      const refStr = typoRef ? `\`${typoRef.figmaKey}\`` : '—';
      const codeMatch = gap.typography.matched.some((e) => e.figmaKey === t.figmaKey);
      lines.push(`| \`${t.figmaKey}\` | \`${t.rawValue}px\` | ${refStr} | ${codeMatch ? '✅ Matched' : '—'} |`);
    }
  }

  // Spacing
  lines.push('', '## Spacing', '');
  lines.push('| Figma Name | Value | Group | DTCG | Code Match | Code Key |');
  lines.push('|------------|-------|-------|------|------------|----------|');
  for (const t of tokens.spacing) {
    const isInComponent = /in component/i.test(t.figmaKey);
    const tier = isInComponent ? 'C' : 'S';
    const matchEntry = gap.spacing.matched.find((e) => e.figmaKey === t.figmaKey);
    const spMatch = matchEntry ? '✅ Matched' : gap.spacing.figmaOnly.some((e) => e.figmaKey === t.figmaKey) ? '⚠️ Figma-only' : '—';
    const codeKey = matchEntry?.codeKey ?? '—';
    lines.push(`| \`${t.figmaKey}\` | \`${t.rawValue}px\` | ${t.group} | ${tier} | ${spMatch} | \`${codeKey}\` |`);
  }

  if (gap.spacing.codeOnly.length > 0) {
    lines.push('', '### Spacing in `commerce-theme` not in Figma', '');
    lines.push('| Code Key | Value |');
    lines.push('|----------|-------|');
    for (const e of gap.spacing.codeOnly) {
      lines.push(`| \`${e.codeKey}\` | \`${e.codeValue}\` |`);
    }
  }

  // Shadows
  lines.push('', '## Shadows', '');
  lines.push('| Figma Name | First Layer | Code Match | Code Key |');
  lines.push('|------------|-------------|------------|----------|');
  for (const t of tokens.shadows) {
    const matchEntry = gap.shadows.matched.find((e) => e.figmaKey === t.figmaKey);
    const shadowMatch = matchEntry ? '✅ Matched' : '⚠️ Figma-only';
    const codeKey = matchEntry?.codeKey ?? '—';
    const firstEffect = t.rawValue.split(';')[0].trim().slice(0, 80);
    lines.push(`| \`${t.figmaKey}\` | ${firstEffect}... | ${shadowMatch} | \`${codeKey}\` |`);
  }

  if (gap.shadows.codeOnly.length > 0) {
    lines.push('', '### Shadows in `commerce-theme` not in Figma', '');
    lines.push('| Code Key | First Layer |');
    lines.push('|----------|-------------|');
    for (const e of gap.shadows.codeOnly) {
      lines.push(`| \`${e.codeKey}\` | ${(e.codeValue ?? '').slice(0, 80)}... |`);
    }
  }

  // Strokes
  lines.push('', '## Strokes (Border Widths)', '');
  lines.push('| Figma Name | Value |');
  lines.push('|------------|-------|');
  for (const t of tokens.strokes) {
    lines.push(`| \`${t.figmaKey}\` | \`${t.rawValue}px\` |`);
  }

  // Layout & Grid (columns, viewport — NOT font sizes)
  lines.push('', '## Layout & Grid', '');
  lines.push('| Figma Name | Value | Group |');
  lines.push('|------------|-------|-------|');
  for (const t of tokens.layout) {
    lines.push(`| \`${t.figmaKey}\` | \`${t.rawValue}\` | ${t.group} |`);
  }

  lines.push('', '---', `*Generated by \`build-inventory.ts\`*`);
  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Doc 02: Component Inventory (adds functional category column)
// ---------------------------------------------------------------------------

function doc02ComponentInventory(components: FigmaComponent[]): string {
  const lines: string[] = [
    '# 02 · Component Inventory',
    '',
    `> **${components.length} total components** extracted from the "Molecules & Atoms" Figma page.`,
    '',
  ];

  const sections: Section[] = ['atoms', 'molecules', 'inputs', 'other'];
  for (const section of sections) {
    const group = components.filter((c) => c.section === section);
    lines.push(`## ${SECTION_LABELS[section]} (${group.length})`, '');
    lines.push('| Component | Category | Variants | Property Axes | Responsive | HTML Element | Figma ID |');
    lines.push('|-----------|----------|----------|---------------|------------|--------------|----------|');
    for (const c of group.sort((a, b) => a.name.localeCompare(b.name))) {
      const axes = Object.keys(c.properties).join(', ');
      const responsive = c.hasResponsive ? '✅' : '—';
      const cat = CATEGORY_LABELS[c.functionalCategory];
      lines.push(`| ${c.name} | ${cat} | ${c.variantCount} | ${axes || '—'} | ${responsive} | \`<${c.suggestedHtmlElement}>\` | \`${c.figmaId}\` |`);
    }
    lines.push('');
  }

  lines.push('---', `*Generated by \`build-inventory.ts\`*`);
  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Doc 03: State Completeness Matrix
// ---------------------------------------------------------------------------

const EXPECTED_STATES = ['Default', 'Hover', 'Focus', 'Active', 'Disabled', 'Error', 'Loading', 'Success', 'Selected'];

function doc03StateMatrix(components: FigmaComponent[]): string {
  const lines: string[] = [
    '# 03 · State Completeness Matrix',
    '',
    '> **Legend:** `Y` = state exists with proper naming · `??` = state exists with inconsistent name · `—` = not applicable · `MISS` = expected but absent',
    '',
    '**Note:** Components without a `State` property axis are excluded from this table.',
    '',
  ];

  const stateComponents = components.filter(
    (c) => c.properties['State'] || c.properties['Property 1']
  );

  lines.push(`| Component | Section | ${EXPECTED_STATES.join(' | ')} |`);
  lines.push(`|-----------|---------|${EXPECTED_STATES.map(() => '---').join('|')}|`);

  for (const c of stateComponents.sort((a, b) => a.name.localeCompare(b.name))) {
    const stateValues = c.properties['State'] ?? c.properties['Property 1'] ?? [];
    const normalizedValues = stateValues.map((v) => v.toLowerCase());

    const cells = EXPECTED_STATES.map((state) => {
      const lower = state.toLowerCase();
      if (normalizedValues.includes(lower) || normalizedValues.includes(`${lower}d`)) return 'Y';
      const hasInconsistent = stateValues.some((v) => isInconsistentStateName(v));
      if (hasInconsistent) return '??';
      if (state === 'Error' || state === 'Loading' || state === 'Success' || state === 'Selected') return '—';
      if ((state === 'Hover' || state === 'Focus' || state === 'Active' || state === 'Disabled') && stateValues.length > 0) return 'MISS';
      return '—';
    });

    const inconsistentNames = stateValues.filter((v) => isInconsistentStateName(v));
    const noteStr = inconsistentNames.length > 0 ? ` ⚠️ *${inconsistentNames.join(', ')}*` : '';

    lines.push(`| ${c.name}${noteStr} | ${SECTION_LABELS[c.section]} | ${cells.join(' | ')} |`);
  }

  lines.push('', '## Inconsistency Summary', '');
  const allInconsistentNames = new Set<string>();
  for (const c of stateComponents) {
    const stateValues = c.properties['State'] ?? c.properties['Property 1'] ?? [];
    for (const v of stateValues) {
      if (isInconsistentStateName(v)) allInconsistentNames.add(`${c.name}: "${v}"`);
    }
  }

  if (allInconsistentNames.size > 0) {
    lines.push('The following components have auto-generated state values that should be renamed in Figma:', '');
    for (const item of allInconsistentNames) {
      lines.push(`- ${item}`);
    }
  } else {
    lines.push('No inconsistent state names detected. ✅');
  }

  lines.push('', '---', `*Generated by \`build-inventory.ts\`*`);
  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Doc 04: Responsive Catalog
// ---------------------------------------------------------------------------

function doc04ResponsiveCatalog(components: FigmaComponent[]): string {
  const lines: string[] = [
    '# 04 · Responsive Pattern Catalog',
    '',
    '> Breakpoints implied by Figma frame widths: **Desktop** = 1440px · **Tablet** = 834px · **Mobile** = 390px',
    '',
  ];

  const fullyResponsive = components.filter((c) => {
    const sizes = (c.properties['Size'] ?? []).map((v) => v.toLowerCase());
    return (
      c.hasResponsive ||
      (sizes.includes('desktop') && sizes.includes('tablet') && sizes.includes('mobile'))
    );
  });

  const partiallyResponsive = components.filter((c) => {
    if (fullyResponsive.includes(c)) return false;
    const sizes = (c.properties['Size'] ?? []).map((v) => v.toLowerCase());
    return sizes.includes('desktop') || sizes.includes('tablet') || sizes.includes('mobile') || c.hasResponsive;
  });

  const notResponsive = components.filter(
    (c) => !fullyResponsive.includes(c) && !partiallyResponsive.includes(c)
  );

  lines.push(`## ✅ Fully Responsive (${fullyResponsive.length})`, '');
  lines.push('| Component | Section | Breakpoint Variants |');
  lines.push('|-----------|---------|---------------------|');
  for (const c of fullyResponsive.sort((a, b) => a.name.localeCompare(b.name))) {
    const sizes = (c.properties['Size'] ?? []).filter((v) => /desktop|tablet|mobile/i.test(v)).join(', ');
    lines.push(`| ${c.name} | ${SECTION_LABELS[c.section]} | ${sizes || 'Desktop, Tablet, Mobile'} |`);
  }

  lines.push('', `## ⚠️ Partially Responsive (${partiallyResponsive.length})`, '');
  lines.push('| Component | Section | Has | Missing |');
  lines.push('|-----------|---------|-----|---------|');
  for (const c of partiallyResponsive.sort((a, b) => a.name.localeCompare(b.name))) {
    const has = (c.properties['Size'] ?? []).filter((v) => /desktop|tablet|mobile/i.test(v)).join(', ');
    const all = ['Desktop', 'Tablet', 'Mobile'];
    const missing = all.filter((bp) => !has.toLowerCase().includes(bp.toLowerCase())).join(', ');
    lines.push(`| ${c.name} | ${SECTION_LABELS[c.section]} | ${has || '—'} | ${missing} |`);
  }

  lines.push('', `## — Not Responsive (${notResponsive.length})`, '');
  lines.push('| Component | Section | Sizes Available | HTML Element |');
  lines.push('|-----------|---------|-----------------|--------------|');
  for (const c of notResponsive.sort((a, b) => a.name.localeCompare(b.name))) {
    const sizes = (c.properties['Size'] ?? []).join(', ') || '—';
    lines.push(`| ${c.name} | ${SECTION_LABELS[c.section]} | ${sizes} | \`<${c.suggestedHtmlElement}>\` |`);
  }

  lines.push('', '---', `*Generated by \`build-inventory.ts\`*`);
  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Doc 05: Variant Analysis (algorithmic consolidation + state axis pollution)
// ---------------------------------------------------------------------------

function doc05VariantAnalysis(components: FigmaComponent[], axes: VariantAxis[]): string {
  const lines: string[] = [
    '# 05 · Variant Analysis',
    '',
    '## Property Axes Used Across Components',
    '',
    '| Axis | # Components | Values | Components |',
    '|------|-------------|--------|------------|',
  ];

  for (const ax of axes) {
    lines.push(`| **${ax.axis}** | ${ax.components.length} | ${ax.values.join(', ')} | ${ax.components.join(', ')} |`);
  }

  // State axis pollution
  lines.push('', '## ⚠️ State Axis Quality Issues', '');
  lines.push('The `State` property axis contains values that are not interaction states. These should be moved to separate axes in Figma.', '');

  const stateAxis = axes.find((a) => a.axis === 'State');
  if (stateAxis) {
    const breakpoints = stateAxis.values.filter((v) => NON_STATE_BREAKPOINTS.has(v));
    const inputTypes = stateAxis.values.filter((v) => NON_STATE_INPUT_TYPES.has(v));
    const typos = stateAxis.values.filter((v) => STATE_TYPOS[v]);
    const autoGen = stateAxis.values.filter((v) => isInconsistentStateName(v));

    if (breakpoints.length > 0) {
      lines.push(`**Breakpoint values mixed into State axis:** \`${breakpoints.join('`, `')}\``);
      lines.push('→ These should be the `Size` axis (Desktop/Tablet/Mobile), not State.', '');
    }
    if (inputTypes.length > 0) {
      lines.push(`**Input type values mixed into State axis:** \`${inputTypes.join('`, `')}\``);
      lines.push('→ These should be the `Style` axis (Checkbox/Radio), not State.', '');
    }
    if (typos.length > 0) {
      lines.push('**Typos / inconsistent naming in State axis:**', '');
      lines.push('| Found | Should Be |');
      lines.push('|-------|-----------|');
      for (const t of typos) {
        lines.push(`| \`${t}\` | \`${STATE_TYPOS[t]}\` |`);
      }
      lines.push('');
    }
    if (autoGen.length > 0) {
      lines.push(`**Auto-generated state names:** \`${autoGen.join('`, `')}\``);
      lines.push('→ Replace with descriptive names.', '');
    }
  }

  // Naming inconsistencies (auto-generated values in any axis)
  lines.push('', '## Auto-Generated Property Values', '');
  const issues: Array<{ component: string; axis: string; badValues: string[] }> = [];
  for (const c of components) {
    for (const [axis, values] of Object.entries(c.properties)) {
      const badVals = values.filter((v) => isInconsistentStateName(v));
      if (badVals.length > 0) issues.push({ component: c.name, axis, badValues: badVals });
    }
  }

  if (issues.length > 0) {
    lines.push('| Component | Axis | Bad Value(s) | Action |');
    lines.push('|-----------|------|-------------|--------|');
    for (const issue of issues) {
      lines.push(`| ${issue.component} | ${issue.axis} | \`${issue.badValues.join('`, `')}\` | Rename with descriptive value in Figma |`);
    }
  } else {
    lines.push('No auto-generated names detected. ✅');
  }

  // Consolidation opportunities (algorithmic)
  lines.push('', '## 💡 Consolidation Opportunities', '');
  lines.push('Detected algorithmically from shared axes, name stems, and duplicate frames.', '');

  const candidates = detectConsolidationCandidates(components);
  if (candidates.length > 0) {
    lines.push('| Component A | Component B | Reason |');
    lines.push('|-------------|-------------|--------|');
    for (const c of candidates) {
      lines.push(`| ${c.compA} | ${c.compB} | ${c.reason} |`);
    }
  } else {
    lines.push('No consolidation candidates detected.');
  }

  // Variant explosion
  lines.push('', '## 💥 Variant Count Overview (Top 20)', '');
  lines.push('| Component | Section | Variant Count | Axes |');
  lines.push('|-----------|---------|---------------|------|');
  const sortedByVariants = [...components].sort((a, b) => b.variantCount - a.variantCount);
  for (const c of sortedByVariants.slice(0, 20)) {
    const axeCount = Object.keys(c.properties).length;
    lines.push(`| ${c.name} | ${SECTION_LABELS[c.section]} | ${c.variantCount} | ${axeCount} |`);
  }

  lines.push('', '---', `*Generated by \`build-inventory.ts\`*`);
  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Doc 06: Dependency Graph
// ---------------------------------------------------------------------------

function doc06DependencyGraph(components: FigmaComponent[]): string {
  const lines: string[] = [
    '# 06 · Component Dependency Graph',
    '',
    '> Initial mappings inferred from component names and Figma section hierarchy. Refine as needed.',
    '',
    '## Full Hierarchy',
    '',
    '```mermaid',
    'graph TD',
  ];

  lines.push('  subgraph htmlElements ["HTML Elements"]');
  const htmlEls = [...new Set(components.map((c) => c.suggestedHtmlElement))];
  for (const el of htmlEls) {
    const id = el.replace(/[^a-zA-Z0-9]/g, '_');
    lines.push(`    ${id}["&lt;${el}&gt;"]`);
  }
  lines.push('  end');

  const atoms = components.filter((c) => c.section === 'atoms');
  lines.push('  subgraph atomsGroup ["Atoms"]');
  for (const c of atoms) {
    const id = c.name.replace(/[^a-zA-Z0-9]/g, '_');
    lines.push(`    ${id}["${c.name}"]`);
  }
  lines.push('  end');

  const molecules = components.filter((c) => c.section === 'molecules');
  lines.push('  subgraph moleculesGroup ["Molecules"]');
  for (const c of molecules) {
    const id = c.name.replace(/[^a-zA-Z0-9]/g, '_');
    lines.push(`    ${id}["${c.name}"]`);
  }
  lines.push('  end');

  const inputs = components.filter((c) => c.section === 'inputs');
  lines.push('  subgraph inputsGroup ["Inputs"]');
  for (const c of inputs) {
    const id = c.name.replace(/[^a-zA-Z0-9]/g, '_');
    lines.push(`    ${id}["${c.name}"]`);
  }
  lines.push('  end');

  lines.push('', '  %% HTML to Atom and Input connections');
  for (const c of [...atoms, ...inputs]) {
    const compId = c.name.replace(/[^a-zA-Z0-9]/g, '_');
    const htmlId = c.suggestedHtmlElement.replace(/[^a-zA-Z0-9]/g, '_');
    lines.push(`  ${htmlId} --> ${compId}`);
  }

  lines.push('', '  %% Atom/Input to Molecule connections');
  for (const [molName, deps] of Object.entries(DEPENDENCY_MAP)) {
    const mol = components.find((c) => c.name === molName);
    if (!mol || mol.section !== 'molecules') continue;
    const molId = molName.replace(/[^a-zA-Z0-9]/g, '_');
    for (const dep of deps) {
      const depId = dep.replace(/[^a-zA-Z0-9]/g, '_');
      lines.push(`  ${depId} --> ${molId}`);
    }
  }
  lines.push('```');

  lines.push('', '## Atoms with Internal Dependencies', '');
  lines.push('```mermaid', 'graph TD');
  lines.push('  subgraph atomDeps ["Atom Internal Dependencies"]');
  for (const [name, deps] of Object.entries(DEPENDENCY_MAP)) {
    const comp = components.find((c) => c.name === name && c.section === 'atoms');
    if (!comp || deps.length === 0) continue;
    const parentId = name.replace(/[^a-zA-Z0-9]/g, '_');
    for (const dep of deps) {
      const depId = dep.replace(/[^a-zA-Z0-9]/g, '_');
      lines.push(`    ${depId}["${dep}"] --> ${parentId}["${name}"]`);
    }
  }
  lines.push('  end', '```');

  lines.push('', '## Molecule → Atom Dependencies', '');
  lines.push('| Molecule | Depends On |');
  lines.push('|----------|------------|');
  for (const c of molecules.sort((a, b) => a.name.localeCompare(b.name))) {
    const deps = DEPENDENCY_MAP[c.name] ?? [];
    lines.push(`| ${c.name} | ${deps.length > 0 ? deps.join(', ') : '—'} |`);
  }

  lines.push('', '---', `*Generated by \`build-inventory.ts\`*`);
  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Doc 07: Priority Dashboard (with dependency weight)
// ---------------------------------------------------------------------------

interface PriorityScore {
  component: FigmaComponent;
  sectionScore: number;
  variantScore: number;
  stateScore: number;
  responsiveScore: number;
  depScore: number;
  total: number;
  recommendation: string;
}

function scorePriority(c: FigmaComponent, depWeight: Map<string, number>): PriorityScore {
  const sectionScore = c.section === 'atoms' ? 3 : c.section === 'inputs' ? 2 : c.section === 'molecules' ? 1 : 0;

  const stateValues = c.properties['State'] ?? c.properties['Property 1'] ?? [];
  const inconsistentCount = stateValues.filter((v) => isInconsistentStateName(v)).length;
  const variantScore = inconsistentCount === 0 ? 2 : Math.max(0, 2 - inconsistentCount);

  const hasDefaultStates =
    stateValues.some((v) => /default/i.test(v)) &&
    stateValues.some((v) => /hover/i.test(v)) &&
    stateValues.some((v) => /disabled?/i.test(v));
  const stateScore = hasDefaultStates ? 2 : stateValues.length > 0 ? 1 : 0;

  const responsiveScore = c.hasResponsive ? 1 : 0;

  // Dependency weight: how many other components depend on this one
  const dependents = depWeight.get(c.name) ?? 0;
  const depScore = dependents >= 3 ? 2 : dependents >= 1 ? 1 : 0;

  const total = sectionScore + variantScore + stateScore + responsiveScore + depScore;

  let recommendation: string;
  if (inconsistentCount > 0) {
    recommendation = '⚠️ Needs Figma cleanup (inconsistent state names)';
  } else if (total >= 7) {
    recommendation = '✅ Build first — high dependency weight';
  } else if (total >= 5) {
    recommendation = '✅ Ready to build';
  } else if (total >= 3) {
    recommendation = '🔄 Build with minor caveats';
  } else {
    recommendation = '⏳ Address coverage gaps first';
  }

  return { component: c, sectionScore, variantScore, stateScore, responsiveScore, depScore, total, recommendation };
}

function doc07PriorityDashboard(components: FigmaComponent[]): string {
  const depWeight = buildDependencyWeight();

  const lines: string[] = [
    '# 07 · Build Priority Dashboard',
    '',
    '> **Scoring:** Section (atoms=3, inputs=2, molecules=1) + Variant quality (clean names=2) + State coverage (default+hover+disabled=2) + Responsive (1) + **Dependency weight** (3+ dependents=2, 1-2=1). Max = 10.',
    '',
  ];

  const scores = components
    .map((c) => scorePriority(c, depWeight))
    .sort((a, b) => b.total - a.total || a.component.name.localeCompare(b.component.name));

  lines.push('| Component | Section | Sec | Var | State | Resp | Dep | **Total** | Recommendation |');
  lines.push('|-----------|---------|-----|-----|-------|------|-----|-----------|----------------|');
  for (const s of scores) {
    const depCount = depWeight.get(s.component.name) ?? 0;
    const depLabel = depCount > 0 ? `${s.depScore} (${depCount})` : '0';
    lines.push(
      `| ${s.component.name} | ${SECTION_LABELS[s.component.section]} | ${s.sectionScore} | ${s.variantScore} | ${s.stateScore} | ${s.responsiveScore} | ${depLabel} | **${s.total}** | ${s.recommendation} |`
    );
  }

  const ready = scores.filter((s) => s.recommendation.startsWith('✅')).length;
  const minor = scores.filter((s) => s.recommendation.startsWith('🔄')).length;
  const cleanup = scores.filter((s) => s.recommendation.startsWith('⚠️')).length;
  const deferred = scores.filter((s) => s.recommendation.startsWith('⏳')).length;

  lines.push('', '## Summary', '');
  lines.push('| Status | Count |', '|--------|-------|');
  lines.push(`| ✅ Ready / high priority | ${ready} |`);
  lines.push(`| 🔄 Build with minor caveats | ${minor} |`);
  lines.push(`| ⚠️ Needs Figma cleanup | ${cleanup} |`);
  lines.push(`| ⏳ Deferred | ${deferred} |`);

  lines.push('', '---', `*Generated by \`build-inventory.ts\`*`);
  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Doc 08: Functional Taxonomy
// ---------------------------------------------------------------------------

function doc08Taxonomy(components: FigmaComponent[], taxonomy: Taxonomy): string {
  const lines: string[] = [
    '# 08 · Functional Taxonomy',
    '',
    '> A two-axis classification: **Atomic level** (Atom/Molecule/Input/Other) from Figma section · **Functional category** (what the component does) proposed for code organization.',
    '',
    '## Category Overview',
    '',
    '```mermaid',
    'graph TD',
    '  DesignSystem["Logos Design System"]',
  ];

  for (const cat of taxonomy.categories) {
    const id = cat.id.replace(/-/g, '_');
    lines.push(`  DesignSystem --> ${id}["${cat.label}\\n(${cat.components.length} components)"]`);
  }
  lines.push('```');

  lines.push('', '## Category Definitions', '');
  for (const cat of taxonomy.categories) {
    lines.push(`### ${cat.label} (${cat.components.length})`, '');
    lines.push(`> ${cat.description}`, '');
    if (cat.components.length > 0) {
      lines.push(cat.components.map((c) => `- ${c}`).join('\n'));
    }
    lines.push('');
  }

  // Dual-axis table
  lines.push('## Dual-Axis Classification', '');
  lines.push('Every component mapped to both its Figma atomic level and proposed functional category.', '');
  lines.push('| Component | Atomic Level | Functional Category | Proposed Code Name |');
  lines.push('|-----------|-------------|--------------------|--------------------|');
  for (const c of [...components].sort((a, b) => a.name.localeCompare(b.name))) {
    lines.push(`| ${c.name} | ${SECTION_LABELS[c.section]} | ${CATEGORY_LABELS[c.functionalCategory]} | \`${c.proposedCodeName}\` |`);
  }

  // Proposed folder structure
  lines.push('', '## Proposed Code Folder Structure', '');
  lines.push('Based on the functional taxonomy, components should be organized as follows in `CommerceComponents/packages/`:');
  lines.push('');
  lines.push('```');
  for (const line of taxonomy.proposedFolderStructure) {
    lines.push(line);
  }
  lines.push('```');

  lines.push('', '## Note on "Other" Reclassification', '');
  lines.push('The 6 components currently in Figma\'s "Other" section are assigned functional categories as follows:', '');
  const others = components.filter((c) => c.section === 'other');
  lines.push('| Component | Proposed Category | Rationale |');
  lines.push('|-----------|------------------|-----------|');
  for (const c of others) {
    const rationale: Record<string, string> = {
      'Badges and Tags': 'Standalone display element — atom-level data display',
      'Price and Label': 'Commerce-specific display atom showing price info',
      'Sale Percentage': 'Badge variant for promotional pricing',
      'Image Ratios': 'Layout constraint helper, not a component — consider removing from inventory',
      'Product Images': 'Commerce-specific image display atom',
      'List': 'Generic layout/text atom used inside content sections',
    };
    lines.push(`| ${c.name} | ${CATEGORY_LABELS[c.functionalCategory]} | ${rationale[c.name] ?? '—'} |`);
  }

  lines.push('', '---', `*Generated by \`build-inventory.ts\`*`);
  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Doc 09: Naming Conventions
// ---------------------------------------------------------------------------

function doc09NamingConventions(components: FigmaComponent[]): string {
  return `# 09 · Naming Conventions

> Proposed naming standards for components, tokens, and property axes to create consistent, predictable identifiers across Figma and code.

## Component Naming Rules

### In Code (React)
1. **PascalCase** for all component names: \`Button\`, \`TextInput\`, \`ProductCard\`
2. **No em-dashes** — replace with nothing or with a word: \`Text Button—Icon Right\` → \`TextButtonIconRight\`
3. **No parentheses** — replace with a descriptor: \`Text Input (single line)\` → \`TextInput\`, \`Text Input (name, two fields)\` → \`TextInputGroup\`
4. **Spell out abbreviations** except: \`CTA\` (established in the brand), \`FAB\` (not recommended — prefer \`FloatingActionButton\`)
5. **No redundant suffixes** — avoid \`Component\`, \`Widget\`, \`Element\` suffixes
6. **Compound words** for composites: \`SectionHeadlineWithCta\` not \`SectionHeadline_With_CTA\`

### In Figma
1. Use the proposed code name as the Figma frame name where possible (enables future auto-generation)
2. Separate words with spaces in Figma: \`Text Input\`, \`Section Headline\`
3. Use em-dashes only for directional variants: \`Text Button—Icon Right\`

### CSS Class Prefix
All components use the \`cc-\` prefix (Commerce Components): \`cc-button\`, \`cc-text-input\`, \`cc-product-card\`

---

## Component Name Mapping

| Figma Name | Proposed Code Name | CSS Class | Category |
|------------|--------------------|-----------|----------|
${components
  .sort((a, b) => a.name.localeCompare(b.name))
  .map((c) => {
    const cssClass = `cc-${c.proposedCodeName
      .replace(/([A-Z])/g, '-$1')
      .toLowerCase()
      .replace(/^-/, '')}`;
    return `| ${c.name} | \`${c.proposedCodeName}\` | \`${cssClass}\` | ${CATEGORY_LABELS[c.functionalCategory]} |`;
  })
  .join('\n')}

---

## Token Naming Rules

### Token Name Format
\`\`\`
{tier}-{category}-{variant}-{property}
\`\`\`

- **Tier prefixes:** none for primitives · \`color-\`, \`spacing-\`, \`shadow-\` for semantic · \`component-{name}-\` for component-scoped
- **All kebab-case:** \`color-brand-primary\`, \`spacing-h-md\`, \`component-button-padding-horizontal\`
- **No camelCase in token names**

### Examples

| Figma Variable | DTCG Token Name | Tier |
|----------------|-----------------|------|
| \`Primary/Logos Blue\` | \`primary-logos-blue\` | Primitive |
| \`Primary/Logos Blue\` (alias) | \`color-brand-primary\` | Semantic |
| \`Deep Colors/Green\` | \`color-feedback-success\` | Semantic |
| \`Spacing \\| Horizontal/MD\` | \`spacing-h-md\` | Semantic |
| \`Spacing \\| In Component/CTA Button - CTA Button \\| Horizontal\` | \`component-button-padding-horizontal\` | Component |

---

## Property Axis Naming Rules

### State Axis
The \`State\` property should only contain **interaction states**:

| ✅ Valid State Values | ❌ Should Move Elsewhere |
|----------------------|--------------------------|
| Default, Hover, Focus, Active, Disabled | Desktop, Tablet, Mobile → use \`Size\` axis |
| Error, Loading, Success, Selected | Checkbox, Radio → use \`Style\` axis |
| Filled, Expanded, Collapsed | Click → remove or use \`State=Active\` |
| On, Off, Checked, Unchecked | Variant4, State2 → rename descriptively |

### Other Axis Standards
- **Size axis:** T-shirt sizes only: \`Small\`, \`Medium\`, \`Large\`, \`X-Large\`. Responsive breakpoints go in \`Size\` too: \`Desktop\`, \`Tablet\`, \`Mobile\`
- **Style axis:** Visual style variants: \`Solid\`, \`Outline\`, \`Ghost\`, \`Dark\`, \`Light\`
- **Type axis:** Semantic variants: \`Primary\`, \`Secondary\`, \`Danger\`, \`CTA (Default)\`
- **Direction axis:** Directional variants: \`Left\`, \`Right\`, \`Next\`, \`Previous\`
- **Background axis:** Surface context: \`Light\`, \`Dark\`, \`Logos Blue\`

---

*Generated by \`build-inventory.ts\`*
`;
}

// ---------------------------------------------------------------------------
// Doc 10: Figma Cleanup Checklist
// ---------------------------------------------------------------------------

function doc10FigmaCleanup(components: FigmaComponent[], gap: GapAnalysis): string {
  const lines: string[] = [
    '# 10 · Figma Cleanup Checklist',
    '',
    '> Actionable items to improve Figma consistency before building components in code.',
    '> Check items off as you address them and re-run `npm run build` to verify.',
    '',
  ];

  // 1. Rename auto-generated state values
  lines.push('## 1. Rename Auto-Generated Property Values', '');
  lines.push('These components have Figma auto-names (`State2`, `Variant4`, etc.) that make it impossible to know what state is being represented.', '');

  const autoGenIssues: Array<{ component: string; axis: string; bad: string }> = [];
  for (const c of components) {
    for (const [axis, values] of Object.entries(c.properties)) {
      for (const v of values) {
        if (isInconsistentStateName(v)) {
          autoGenIssues.push({ component: c.name, axis, bad: v });
        }
      }
    }
  }
  for (const issue of autoGenIssues) {
    lines.push(`- [ ] **${issue.component}** — rename \`${issue.axis}=${issue.bad}\` to a descriptive value`);
  }

  // 2. Fix state axis pollution
  lines.push('', '## 2. Fix State Axis Pollution', '');
  lines.push('Values incorrectly placed in the `State` axis.', '');

  for (const c of components) {
    const stateValues = c.properties['State'] ?? [];
    const breakpointsInState = stateValues.filter((v) => NON_STATE_BREAKPOINTS.has(v));
    const inputTypesInState = stateValues.filter((v) => NON_STATE_INPUT_TYPES.has(v));
    const typosInState = stateValues.filter((v) => STATE_TYPOS[v]);

    for (const v of breakpointsInState) {
      lines.push(`- [ ] **${c.name}** — move \`State=${v}\` to the \`Size\` axis`);
    }
    for (const v of inputTypesInState) {
      lines.push(`- [ ] **${c.name}** — move \`State=${v}\` to the \`Style\` axis`);
    }
    for (const v of typosInState) {
      lines.push(`- [ ] **${c.name}** — rename \`State=${v}\` to \`State=${STATE_TYPOS[v]}\``);
    }
  }

  // 3. Deduplicate frames
  lines.push('', '## 3. Deduplicate Component Frames', '');
  lines.push('Components with duplicate names that appear twice in Figma:', '');
  const nameCounts = new Map<string, string[]>();
  for (const c of components) {
    if (!nameCounts.has(c.name)) nameCounts.set(c.name, []);
    nameCounts.get(c.name)!.push(c.figmaId);
  }
  let hasDuplicates = false;
  for (const [name, ids] of nameCounts.entries()) {
    if (ids.length > 1) {
      hasDuplicates = true;
      lines.push(`- [ ] **${name}** — appears ${ids.length} times (IDs: ${ids.join(', ')}) — delete or rename the duplicate`);
    }
  }
  if (!hasDuplicates) lines.push('No duplicates found. ✅');

  // 4. Add missing critical states
  lines.push('', '## 4. Add Missing Critical States', '');
  lines.push('Components missing Hover, Focus, or Disabled states (minimum viable interactive states).', '');

  const missStates = ['Hover', 'Disabled'];
  for (const c of components) {
    const stateValues = (c.properties['State'] ?? []).map((v) => v.toLowerCase());
    if (stateValues.length === 0) continue;
    const missing = missStates.filter((s) => !stateValues.includes(s.toLowerCase()));
    if (missing.length > 0) {
      lines.push(`- [ ] **${c.name}** — add \`${missing.join(', ')}\` state variant(s)`);
    }
  }

  // 5. Reclassify "Other" section
  lines.push('', '## 5. Reclassify "Other" Section Components', '');
  lines.push('Move components out of the catch-all "Other" Figma section into their proper atomic sections.', '');
  const others = components.filter((c) => c.section === 'other');
  const reclassify: Record<string, string> = {
    'Badges and Tags': 'Atoms',
    'Price and Label': 'Atoms',
    'Sale Percentage': 'Atoms',
    'List': 'Atoms',
    'Product Images': 'Atoms',
    'Image Ratios': 'Consider removing — this is a layout constraint, not a component',
  };
  for (const c of others) {
    lines.push(`- [ ] **${c.name}** → move to **${reclassify[c.name] ?? 'Atoms'}** section`);
  }

  // 6. Standardize responsive coverage
  lines.push('', '## 6. Add Responsive Variants', '');
  lines.push('Key molecules/atoms that should have Desktop + Tablet + Mobile variants but currently do not.', '');

  const highPriorityForResponsive = ['Button', 'Text Input (single line)', 'Dropdown', 'Search Field', 'Toast Bar', 'Carousel Product', 'Product Content'];
  for (const name of highPriorityForResponsive) {
    const comp = components.find((c) => c.name === name);
    if (comp && !comp.hasResponsive) {
      lines.push(`- [ ] **${name}** — add Desktop, Tablet, Mobile size variants`);
    }
  }

  // 7. Token implementation gaps
  lines.push('', '## 7. Implement Missing Tokens in Code', '');
  lines.push('Figma variables that have no matching token in `commerce-theme`.', '');

  lines.push('', '**Colors (in Figma, not in code):**');
  for (const e of gap.colors.figmaOnly) {
    lines.push(`- [ ] Add \`${e.figmaKey}\` (\`${e.figmaValue}\`) to \`commerce-theme/src/colors.ts\``);
  }

  lines.push('', '**Spacing (in Figma, not in code):**');
  for (const e of gap.spacing.figmaOnly) {
    lines.push(`- [ ] Add \`${e.figmaKey}\` (\`${e.figmaValue}\`) to \`commerce-theme/src/spacing.ts\``);
  }

  lines.push('', '**Shadows (in Figma, not in code):**');
  for (const e of gap.shadows.figmaOnly) {
    lines.push(`- [ ] Add \`${e.figmaKey}\` to \`commerce-theme/src/shadows.ts\``);
  }

  // 8. Review code-only tokens
  lines.push('', '## 8. Audit Code-Only Tokens', '');
  lines.push('Tokens that exist in `commerce-theme` but have no Figma variable. These are either orphaned (remove) or missing from Figma (add variable).', '');

  if (gap.colors.codeOnly.length > 0) {
    lines.push('', '**Code-only colors:**');
    for (const e of gap.colors.codeOnly) {
      lines.push(`- [ ] \`${e.codeKey}\` (\`${e.codeValue}\`) — add to Figma or remove from \`colors.ts\``);
    }
  }

  if (gap.spacing.codeOnly.length > 0) {
    lines.push('', '**Code-only spacing:**');
    for (const e of gap.spacing.codeOnly) {
      lines.push(`- [ ] \`${e.codeKey}\` (\`${e.codeValue}\`) — add to Figma or remove from \`spacing.ts\``);
    }
  }

  lines.push('', '---', `*Generated by \`build-inventory.ts\`*`);
  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// README (updated with new docs)
// ---------------------------------------------------------------------------

function readme(components: FigmaComponent[], tokens: TokenCategory, gap: GapAnalysis): string {
  const totalVariants = components.reduce((s, c) => s + c.variantCount, 0);
  const responsiveCount = components.filter((c) => c.hasResponsive).length;
  const catCounts = Object.entries(CATEGORY_LABELS)
    .map(([id, label]) => `| ${label} | ${components.filter((c) => c.functionalCategory === id).length} |`)
    .join('\n');

  return `# Design System Inventory

> Logos Brand Components — generated from Figma MCP data.
> **Re-generate:** update \`raw/\` files then run \`npm run build\` in this directory.

## Stats

| | Count |
|--|-------|
| Total components | ${components.length} |
| Total variants | ${totalVariants} |
| Responsive components | ${responsiveCount} |
| Figma color tokens | ${tokens.colors.length} |
| Colors matched in \`commerce-theme\` | ${gap.colors.matched.length} |
| Colors Figma-only (need code impl) | ${gap.colors.figmaOnly.length} |
| Colors code-only (orphaned) | ${gap.colors.codeOnly.length} |

## By Atomic Level

| Level | Count |
|-------|-------|
| Atoms | ${components.filter((c) => c.section === 'atoms').length} |
| Molecules | ${components.filter((c) => c.section === 'molecules').length} |
| Inputs & Forms | ${components.filter((c) => c.section === 'inputs').length} |
| Other | ${components.filter((c) => c.section === 'other').length} |

## By Functional Category

| Category | Count |
|----------|-------|
${catCounts}

## Documents

| # | Document | Description |
|---|----------|-------------|
| 01 | [Token Map](./01-token-map.md) | All Figma variables with DTCG tiers, swatches, and commerce-theme match status |
| 02 | [Component Inventory](./02-component-inventory.md) | All 71 components with functional category, variants, axes, and HTML mappings |
| 03 | [State Completeness Matrix](./03-state-matrix.md) | Cross-component interaction state coverage |
| 04 | [Responsive Catalog](./04-responsive-catalog.md) | Components grouped by responsive coverage |
| 05 | [Variant Analysis](./05-variant-analysis.md) | State axis quality, naming consistency, consolidation opportunities |
| 06 | [Dependency Graph](./06-dependency-graph.md) | HTML → Atom → Molecule relationships (Mermaid) |
| 07 | [Priority Dashboard](./07-priority-dashboard.md) | Scored build order including dependency weight |
| 08 | [Functional Taxonomy](./08-taxonomy.md) | Dual-axis classification, Mermaid category tree, proposed folder structure |
| 09 | [Naming Conventions](./09-naming-conventions.md) | Component/token/axis naming rules with Figma-to-code mapping |
| 10 | [Figma Cleanup Checklist](./10-figma-cleanup.md) | Actionable checkboxes for every detected issue |

## Data Files

| File | Description |
|------|-------------|
| \`data/tokens.json\` | All Figma variables by category (incl. fontSizes) |
| \`data/components.json\` | All 71 components with functionalCategory and proposedCodeName |
| \`data/variant-axes.json\` | Deduplicated property axes across all components |
| \`data/taxonomy.json\` | Category definitions and proposed folder structure |
| \`data/gap-analysis.json\` | Figma vs. commerce-theme token comparison |
| \`data/dtcg/primitives.json\` | Tier 1 DTCG tokens (raw values) |
| \`data/dtcg/semantic.json\` | Tier 2 DTCG tokens (intent-based aliases) |
| \`data/dtcg/component.json\` | Tier 3 DTCG tokens (component-scoped) |

## Pipeline

\`\`\`
raw/figma-metadata.xml     ─┐
raw/figma-variables.json   ─┤─► parse-figma.ts ──► data/*.json + data/taxonomy.json
                            │
commerce-theme/src/*.ts    ─┘─► gap-analysis.ts ──► data/gap-analysis.json
                                map-dtcg.ts ──────► data/dtcg/*.json
                                generate-docs.ts ──► docs/*.md (10 docs + README)
\`\`\`
`;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

export async function generateDocs() {
  console.log('\n=== generate-docs: generating markdown documents ===');

  const components: FigmaComponent[] = readJson('components.json');
  const axes: VariantAxis[] = readJson('variant-axes.json');
  const tokens: TokenCategory = readJson('tokens.json');
  const gap: GapAnalysis = readJson('gap-analysis.json');
  const taxonomy: Taxonomy = readJson('taxonomy.json');

  const docsDir = join(ROOT, 'docs');

  writeDoc(join(docsDir, '01-token-map.md'), doc01TokenMap(tokens, gap));
  writeDoc(join(docsDir, '02-component-inventory.md'), doc02ComponentInventory(components));
  writeDoc(join(docsDir, '03-state-matrix.md'), doc03StateMatrix(components));
  writeDoc(join(docsDir, '04-responsive-catalog.md'), doc04ResponsiveCatalog(components));
  writeDoc(join(docsDir, '05-variant-analysis.md'), doc05VariantAnalysis(components, axes));
  writeDoc(join(docsDir, '06-dependency-graph.md'), doc06DependencyGraph(components));
  writeDoc(join(docsDir, '07-priority-dashboard.md'), doc07PriorityDashboard(components));
  writeDoc(join(docsDir, '08-taxonomy.md'), doc08Taxonomy(components, taxonomy));
  writeDoc(join(docsDir, '09-naming-conventions.md'), doc09NamingConventions(components));
  writeDoc(join(docsDir, '10-figma-cleanup.md'), doc10FigmaCleanup(components, gap));
  writeDoc(join(docsDir, 'README.md'), readme(components, tokens, gap));

  console.log(`  11 documents written to ./docs/`);
}

const isMain = process.argv[1]?.endsWith('generate-docs.ts') || process.argv[1]?.endsWith('generate-docs.js');
if (isMain) generateDocs().catch((e) => { console.error(e); process.exit(1); });
