/**
 * generate-docs.ts
 *
 * Reads all data/*.json files and produces 10 markdown documents + README.
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import type {
  FigmaComponent,
  VariantAxis,
  TokenCategory,
  GapAnalysis,
  Section,
  FunctionalCategory,
  Taxonomy,
  CodeComponent,
  ComponentTier,
  TokenMigrationItem,
  MigrationStatus,
  MigrationPriority,
} from './types.js';

const __dirname = fileURLToPath(new URL('.', import.meta.url));
const ROOT = join(__dirname, '..');

function ensureDir(p: string) {
  if (!existsSync(p)) mkdirSync(p, { recursive: true });
}

function writeDoc(p: string, content: string) {
  ensureDir(dirname(p));
  writeFileSync(p, content, 'utf-8');
  console.log(`  wrote ${p.replace(ROOT, '.')}`);
}

function readJson<T>(name: string): T {
  return JSON.parse(readFileSync(join(ROOT, 'data', name), 'utf-8')) as T;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

const SECTION_LABELS: Record<Section, string> = {
  atoms: 'Atoms',
  molecules: 'Molecules',
  inputs: 'Inputs & Forms',
  other: 'Other',
};

const CATEGORY_LABELS: Record<FunctionalCategory, string> = {
  actions: 'Actions',
  navigation: 'Navigation',
  'data-entry': 'Data Entry',
  'data-display': 'Data Display',
  feedback: 'Feedback & Overlays',
  'content-layout': 'Content Layout',
  product: 'Product',
  selection: 'Selection & Controls',
};

const TIER_LABELS: Record<ComponentTier, string> = {
  primitive: 'Primitive',
  composition: 'Composition',
  'builder-block': 'Builder Block',
};

// Color swatch using placehold.co image (renders on GitHub as a real colored square)
function colorSwatch(hex?: string): string {
  if (!hex || !hex.startsWith('#')) return '';
  const clean = hex.replace(/^#/, '').toUpperCase().padEnd(6, '0').slice(0, 6);
  return `![](https://placehold.co/12x12/${clean}/${clean}.png) `;
}

function matchStatus(figmaKey: string, gapColors: GapAnalysis['colors']): string {
  if (gapColors.matched.some((e) => e.figmaKey === figmaKey)) return '✅ Matched';
  if (gapColors.figmaOnly.some((e) => e.figmaKey === figmaKey)) return '⚠️ Figma-only';
  return '—';
}

// Detect auto-generated Figma state names
function isInconsistentStateName(val: string): boolean {
  return /^state\d+$/i.test(val) || /^variant\d+$/i.test(val) || /^property\s*\d+$/i.test(val);
}

// Values that appear in the State axis but are NOT interaction states
const NON_STATE_BREAKPOINTS = new Set(['Desktop', 'Tablet', 'Mobile']);
const NON_STATE_INPUT_TYPES = new Set(['Checkbox', 'Radio']);
const STATE_TYPOS: Record<string, string> = {
  'Focu': 'Focus',
  'Disable': 'Disabled',
  'Maxium': 'Maximum',
  'Focused': 'Focus (duplicate of "Focus")',
};

function classifyStateValue(val: string): 'valid' | 'breakpoint' | 'inputType' | 'typo' | 'autoGenerated' | 'nonStandard' {
  if (isInconsistentStateName(val)) return 'autoGenerated';
  if (NON_STATE_BREAKPOINTS.has(val)) return 'breakpoint';
  if (NON_STATE_INPUT_TYPES.has(val)) return 'inputType';
  if (STATE_TYPOS[val]) return 'typo';
  return 'valid';
}

// ---------------------------------------------------------------------------
// Dependency map (atom/molecule composition)
// ---------------------------------------------------------------------------

const DEPENDENCY_MAP: Record<string, string[]> = {
  'Button group': ['Button', 'Text Button—Icon Right'],
  'Toast Bar': ['Close Button'],
  'Text Section with Button Group': ['Button', 'Text Button—Icon Right'],
  'Free Trial Card': ['Button', 'Stepper CTA'],
  'Product Content': ['Button', 'Stepper CTA', 'Reviews', 'Badges and Tags', 'Price and Label'],
  'Slider page selector': ['Next-Previous Selector', 'Slider Scroll Bar'],
  'Carousel Product': ['Next-Previous Buttons', 'Slider Scroll Bar', 'Slider page selector'],
  'Section Headline with CTA': ['Button', 'Text Button—Icon Right'],
  'Section Headline': [],
  'Text Section': [],
  'Basic Form': ['Text Input (single line)', 'Dropdown', 'Checkbox', 'Radio Button', 'Button'],
  'Multi-CTA List': ['CTA Row'],
  'Product Grid Card': ['Button', 'Badges and Tags', 'Price and Label', 'Reviews'],
  'Modal Dialog': ['Button', 'Close Button', 'Modal Button Group'],
  'Product Lineup—Single': ['Button', 'Stepper CTA', 'Reviews', 'Badges and Tags', 'Price and Label'],
  'Subnav Dropdown': ['Subnav Dropdown Options'],
  'Button': [],
  'Text Button—Icon Right': [],
  'Text Button—Icon Left': [],
  'Close Button': [],
  'Next-Previous Buttons': [],
  'Expand-Collapse Button': [],
  'Increase-Decrease Buttons': [],
  'Floating Action Button': [],
  'Floating Action Button with Text': [],
  'Play Button': [],
  'Breadcrumbs': [],
  'Simple Menu': [],
  'Button Menu': [],
  'Tabbed Selector': ['Tabbed Selector Button'],
  'Accordion Section': ['Expand-Collapse Button'],
  'Modal Button Group': ['Button'],
  'CTA Row': ['Button'],
  'Category Button': [],
  'Stepper CTA': ['Increase-Decrease Buttons', 'Button'],
  'Stepper Control': ['Increase-Decrease Buttons'],
  'Reviews': ['Star'],
  'Stateful Action Button': ['Button'],
};

function buildDependencyWeight(): Map<string, number> {
  const counts = new Map<string, number>();
  for (const deps of Object.values(DEPENDENCY_MAP)) {
    for (const dep of deps) {
      counts.set(dep, (counts.get(dep) ?? 0) + 1);
    }
  }
  return counts;
}

// ---------------------------------------------------------------------------
// Algorithmic consolidation detection
// ---------------------------------------------------------------------------

interface ConsolidationCandidate {
  compA: string;
  compB: string;
  reason: string;
}

function detectConsolidationCandidates(components: FigmaComponent[]): ConsolidationCandidate[] {
  const candidates: ConsolidationCandidate[] = [];
  const seen = new Set<string>();

  for (let i = 0; i < components.length; i++) {
    for (let j = i + 1; j < components.length; j++) {
      const a = components[i];
      const b = components[j];
      const pairKey = `${a.name}|${b.name}`;
      if (seen.has(pairKey)) continue;
      seen.add(pairKey);

      // Exact duplicate names
      if (a.name === b.name) {
        candidates.push({
          compA: `${a.name} (Figma ID: ${a.figmaId})`,
          compB: `${b.name} (Figma ID: ${b.figmaId})`,
          reason: 'Duplicate frame name — deduplicate in Figma',
        });
        continue;
      }

      const aAxes = Object.keys(a.properties);
      const bAxes = Object.keys(b.properties);
      const aAxeSet = new Set(aAxes);
      const sharedAxes = bAxes.filter((ax) => aAxeSet.has(ax));

      // Identical property axis sets (same axes, different names)
      if (
        sharedAxes.length >= 2 &&
        sharedAxes.length === aAxes.length &&
        sharedAxes.length === bAxes.length &&
        a.functionalCategory === b.functionalCategory
      ) {
        candidates.push({
          compA: a.name,
          compB: b.name,
          reason: `Same property axes [${sharedAxes.join(', ')}] and functional category — consider merging`,
        });
        continue;
      }

      // Common name stem (first meaningful word, length > 4)
      const aStem = a.name.split(/[\s—\-(]/)[0];
      const bStem = b.name.split(/[\s—\-(]/)[0];
      if (
        aStem === bStem &&
        aStem.length > 4 &&
        aStem !== 'Product' && // Product* components are intentionally separate
        aStem !== 'Section'
      ) {
        candidates.push({
          compA: a.name,
          compB: b.name,
          reason: `Common name stem "${aStem}" — review whether these could share a single component with variant props`,
        });
      }
    }
  }

  return candidates;
}

// ---------------------------------------------------------------------------
// Doc 01: Token Map (swatches fixed, Layout split into Font Sizes + Grid)
// ---------------------------------------------------------------------------

function doc01TokenMap(tokens: TokenCategory, gap: GapAnalysis): string {
  const lines: string[] = [
    '# 01 · Design Token Map',
    '',
    '> Generated from Figma Variables (`raw/figma-variables.json`).',
    '> DTCG tiers: **P** = Primitive · **S** = Semantic · **C** = Component.',
    '> Code match: ✅ matched in `commerce-theme` · ⚠️ Figma-only (needs code implementation) · — no data.',
    '',
  ];

  // Colors
  lines.push('## Colors', '');
  lines.push('| | Figma Name | Hex | Group | DTCG | Code Match | Code Key |');
  lines.push('|--|------------|-----|-------|------|------------|----------|');
  for (const t of tokens.colors) {
    const swatch = colorSwatch(t.rawValue);
    const matchEntry = gap.colors.matched.find((e) => e.figmaKey === t.figmaKey);
    const matchStr = matchEntry ? '✅ Matched' : gap.colors.figmaOnly.some((e) => e.figmaKey === t.figmaKey) ? '⚠️ Figma-only' : '—';
    const codeKey = matchEntry?.codeKey ?? '—';
    const tier = /primary|secondary|deep colors|bright/i.test(t.figmaKey) ? 'P' : 'S';
    lines.push(`| ${swatch} | \`${t.figmaKey}\` | \`${t.rawValue.toLowerCase()}\` | ${t.group} | ${tier} | ${matchStr} | \`${codeKey}\` |`);
  }

  if (gap.colors.codeOnly.length > 0) {
    lines.push('', '### Colors in `commerce-theme` not referenced in Figma', '');
    lines.push('These exist in code but have no matching Figma variable. Candidates for removal or addition to Figma.', '');
    lines.push('| | Code Key | Hex |');
    lines.push('|--|----------|-----|');
    for (const e of gap.colors.codeOnly) {
      const swatch = colorSwatch(e.codeValue ?? '#000');
      lines.push(`| ${swatch} | \`${e.codeKey}\` | \`${e.codeValue}\` |`);
    }
  }

  // Typography
  lines.push('', '## Typography', '');
  lines.push('| Figma Name | Family | Weight | Line Height | Letter Spacing | Group |');
  lines.push('|------------|--------|--------|-------------|----------------|-------|');
  for (const t of tokens.typography) {
    const m = t.rawValue.match(/family:\s*"([^"]+)".*weight:\s*(\d+).*lineHeight:\s*([^,]+),.*letterSpacing:\s*([^)]+)/);
    if (m) {
      lines.push(`| \`${t.figmaKey}\` | ${m[1]} | ${m[2]} | ${m[3].trim()} | ${m[4].trim()} | ${t.group} |`);
    }
  }

  // Font Sizes (separated from layout)
  if (tokens.fontSizes.length > 0) {
    lines.push('', '## Font Size References', '');
    lines.push('> These are numeric size values referenced by the typography composite tokens above.', '');
    lines.push('| Figma Name | Size (px) | Referenced By | Code Match |');
    lines.push('|------------|-----------|---------------|------------|');
    for (const t of tokens.fontSizes) {
      const typoRef = tokens.typography.find((ty) => ty.rawValue.includes(t.figmaKey));
      const refStr = typoRef ? `\`${typoRef.figmaKey}\`` : '—';
      const codeMatch = gap.typography.matched.some((e) => e.figmaKey === t.figmaKey);
      lines.push(`| \`${t.figmaKey}\` | \`${t.rawValue}px\` | ${refStr} | ${codeMatch ? '✅ Matched' : '—'} |`);
    }
  }

  // Spacing
  lines.push('', '## Spacing', '');
  lines.push('| Figma Name | Value | Group | DTCG | Code Match | Code Key |');
  lines.push('|------------|-------|-------|------|------------|----------|');
  for (const t of tokens.spacing) {
    const isInComponent = /in component/i.test(t.figmaKey);
    const tier = isInComponent ? 'C' : 'S';
    const matchEntry = gap.spacing.matched.find((e) => e.figmaKey === t.figmaKey);
    const spMatch = matchEntry ? '✅ Matched' : gap.spacing.figmaOnly.some((e) => e.figmaKey === t.figmaKey) ? '⚠️ Figma-only' : '—';
    const codeKey = matchEntry?.codeKey ?? '—';
    lines.push(`| \`${t.figmaKey}\` | \`${t.rawValue}px\` | ${t.group} | ${tier} | ${spMatch} | \`${codeKey}\` |`);
  }

  if (gap.spacing.codeOnly.length > 0) {
    lines.push('', '### Spacing in `commerce-theme` not in Figma', '');
    lines.push('| Code Key | Value |');
    lines.push('|----------|-------|');
    for (const e of gap.spacing.codeOnly) {
      lines.push(`| \`${e.codeKey}\` | \`${e.codeValue}\` |`);
    }
  }

  // Shadows
  lines.push('', '## Shadows', '');
  lines.push('| Figma Name | First Layer | Code Match | Code Key |');
  lines.push('|------------|-------------|------------|----------|');
  for (const t of tokens.shadows) {
    const matchEntry = gap.shadows.matched.find((e) => e.figmaKey === t.figmaKey);
    const shadowMatch = matchEntry ? '✅ Matched' : '⚠️ Figma-only';
    const codeKey = matchEntry?.codeKey ?? '—';
    const firstEffect = t.rawValue.split(';')[0].trim().slice(0, 80);
    lines.push(`| \`${t.figmaKey}\` | ${firstEffect}... | ${shadowMatch} | \`${codeKey}\` |`);
  }

  if (gap.shadows.codeOnly.length > 0) {
    lines.push('', '### Shadows in `commerce-theme` not in Figma', '');
    lines.push('| Code Key | First Layer |');
    lines.push('|----------|-------------|');
    for (const e of gap.shadows.codeOnly) {
      lines.push(`| \`${e.codeKey}\` | ${(e.codeValue ?? '').slice(0, 80)}... |`);
    }
  }

  // Strokes
  lines.push('', '## Strokes (Border Widths)', '');
  lines.push('| Figma Name | Value |');
  lines.push('|------------|-------|');
  for (const t of tokens.strokes) {
    lines.push(`| \`${t.figmaKey}\` | \`${t.rawValue}px\` |`);
  }

  // Layout & Grid (columns, viewport — NOT font sizes)
  lines.push('', '## Layout & Grid', '');
  lines.push('| Figma Name | Value | Group |');
  lines.push('|------------|-------|-------|');
  for (const t of tokens.layout) {
    lines.push(`| \`${t.figmaKey}\` | \`${t.rawValue}\` | ${t.group} |`);
  }

  lines.push('', '---', `*Generated by \`build-inventory.ts\`*`);
  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Doc 02: Component Inventory (adds functional category column)
// ---------------------------------------------------------------------------

function doc02ComponentInventory(components: FigmaComponent[]): string {
  const lines: string[] = [
    '# 02 · Component Inventory',
    '',
    `> **${components.length} total components** extracted from the "Molecules & Atoms" Figma page.`,
    '',
  ];

  const sections: Section[] = ['atoms', 'molecules', 'inputs', 'other'];
  for (const section of sections) {
    const group = components.filter((c) => c.section === section);
    lines.push(`## ${SECTION_LABELS[section]} (${group.length})`, '');
    lines.push('| Component | Category | Variants | Property Axes | Responsive | HTML Element | Figma ID |');
    lines.push('|-----------|----------|----------|---------------|------------|--------------|----------|');
    for (const c of group.sort((a, b) => a.name.localeCompare(b.name))) {
      const axes = Object.keys(c.properties).join(', ');
      const responsive = c.hasResponsive ? '✅' : '—';
      const cat = CATEGORY_LABELS[c.functionalCategory];
      lines.push(`| ${c.name} | ${cat} | ${c.variantCount} | ${axes || '—'} | ${responsive} | \`<${c.suggestedHtmlElement}>\` | \`${c.figmaId}\` |`);
    }
    lines.push('');
  }

  lines.push('---', `*Generated by \`build-inventory.ts\`*`);
  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Doc 03: State Completeness Matrix
// ---------------------------------------------------------------------------

const EXPECTED_STATES = ['Default', 'Hover', 'Focus', 'Active', 'Disabled', 'Error', 'Loading', 'Success', 'Selected'];

function doc03StateMatrix(components: FigmaComponent[]): string {
  const lines: string[] = [
    '# 03 · State Completeness Matrix',
    '',
    '> **Legend:** `Y` = state exists with proper naming · `??` = state exists with inconsistent name · `—` = not applicable · `MISS` = expected but absent',
    '',
    '**Note:** Components without a `State` property axis are excluded from this table.',
    '',
  ];

  const stateComponents = components.filter(
    (c) => c.properties['State'] || c.properties['Property 1']
  );

  lines.push(`| Component | Section | ${EXPECTED_STATES.join(' | ')} |`);
  lines.push(`|-----------|---------|${EXPECTED_STATES.map(() => '---').join('|')}|`);

  for (const c of stateComponents.sort((a, b) => a.name.localeCompare(b.name))) {
    const stateValues = c.properties['State'] ?? c.properties['Property 1'] ?? [];
    const normalizedValues = stateValues.map((v) => v.toLowerCase());

    const cells = EXPECTED_STATES.map((state) => {
      const lower = state.toLowerCase();
      if (normalizedValues.includes(lower) || normalizedValues.includes(`${lower}d`)) return 'Y';
      const hasInconsistent = stateValues.some((v) => isInconsistentStateName(v));
      if (hasInconsistent) return '??';
      if (state === 'Error' || state === 'Loading' || state === 'Success' || state === 'Selected') return '—';
      if ((state === 'Hover' || state === 'Focus' || state === 'Active' || state === 'Disabled') && stateValues.length > 0) return 'MISS';
      return '—';
    });

    const inconsistentNames = stateValues.filter((v) => isInconsistentStateName(v));
    const noteStr = inconsistentNames.length > 0 ? ` ⚠️ *${inconsistentNames.join(', ')}*` : '';

    lines.push(`| ${c.name}${noteStr} | ${SECTION_LABELS[c.section]} | ${cells.join(' | ')} |`);
  }

  lines.push('', '## Inconsistency Summary', '');
  const allInconsistentNames = new Set<string>();
  for (const c of stateComponents) {
    const stateValues = c.properties['State'] ?? c.properties['Property 1'] ?? [];
    for (const v of stateValues) {
      if (isInconsistentStateName(v)) allInconsistentNames.add(`${c.name}: "${v}"`);
    }
  }

  if (allInconsistentNames.size > 0) {
    lines.push('The following components have auto-generated state values that should be renamed in Figma:', '');
    for (const item of allInconsistentNames) {
      lines.push(`- ${item}`);
    }
  } else {
    lines.push('No inconsistent state names detected. ✅');
  }

  lines.push('', '---', `*Generated by \`build-inventory.ts\`*`);
  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Doc 04: Responsive Catalog
// ---------------------------------------------------------------------------

function doc04ResponsiveCatalog(components: FigmaComponent[]): string {
  const lines: string[] = [
    '# 04 · Responsive Pattern Catalog',
    '',
    '> Breakpoints implied by Figma frame widths: **Desktop** = 1440px · **Tablet** = 834px · **Mobile** = 390px',
    '',
  ];

  const fullyResponsive = components.filter((c) => {
    const sizes = (c.properties['Size'] ?? []).map((v) => v.toLowerCase());
    return (
      c.hasResponsive ||
      (sizes.includes('desktop') && sizes.includes('tablet') && sizes.includes('mobile'))
    );
  });

  const partiallyResponsive = components.filter((c) => {
    if (fullyResponsive.includes(c)) return false;
    const sizes = (c.properties['Size'] ?? []).map((v) => v.toLowerCase());
    return sizes.includes('desktop') || sizes.includes('tablet') || sizes.includes('mobile') || c.hasResponsive;
  });

  const notResponsive = components.filter(
    (c) => !fullyResponsive.includes(c) && !partiallyResponsive.includes(c)
  );

  lines.push(`## ✅ Fully Responsive (${fullyResponsive.length})`, '');
  lines.push('| Component | Section | Breakpoint Variants |');
  lines.push('|-----------|---------|---------------------|');
  for (const c of fullyResponsive.sort((a, b) => a.name.localeCompare(b.name))) {
    const sizes = (c.properties['Size'] ?? []).filter((v) => /desktop|tablet|mobile/i.test(v)).join(', ');
    lines.push(`| ${c.name} | ${SECTION_LABELS[c.section]} | ${sizes || 'Desktop, Tablet, Mobile'} |`);
  }

  lines.push('', `## ⚠️ Partially Responsive (${partiallyResponsive.length})`, '');
  lines.push('| Component | Section | Has | Missing |');
  lines.push('|-----------|---------|-----|---------|');
  for (const c of partiallyResponsive.sort((a, b) => a.name.localeCompare(b.name))) {
    const has = (c.properties['Size'] ?? []).filter((v) => /desktop|tablet|mobile/i.test(v)).join(', ');
    const all = ['Desktop', 'Tablet', 'Mobile'];
    const missing = all.filter((bp) => !has.toLowerCase().includes(bp.toLowerCase())).join(', ');
    lines.push(`| ${c.name} | ${SECTION_LABELS[c.section]} | ${has || '—'} | ${missing} |`);
  }

  lines.push('', `## — Not Responsive (${notResponsive.length})`, '');
  lines.push('| Component | Section | Sizes Available | HTML Element |');
  lines.push('|-----------|---------|-----------------|--------------|');
  for (const c of notResponsive.sort((a, b) => a.name.localeCompare(b.name))) {
    const sizes = (c.properties['Size'] ?? []).join(', ') || '—';
    lines.push(`| ${c.name} | ${SECTION_LABELS[c.section]} | ${sizes} | \`<${c.suggestedHtmlElement}>\` |`);
  }

  lines.push('', '---', `*Generated by \`build-inventory.ts\`*`);
  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Doc 05: Variant Analysis (algorithmic consolidation + state axis pollution)
// ---------------------------------------------------------------------------

function doc05VariantAnalysis(components: FigmaComponent[], axes: VariantAxis[]): string {
  const lines: string[] = [
    '# 05 · Variant Analysis',
    '',
    '## Property Axes Used Across Components',
    '',
    '| Axis | # Components | Values | Components |',
    '|------|-------------|--------|------------|',
  ];

  for (const ax of axes) {
    lines.push(`| **${ax.axis}** | ${ax.components.length} | ${ax.values.join(', ')} | ${ax.components.join(', ')} |`);
  }

  // State axis pollution
  lines.push('', '## ⚠️ State Axis Quality Issues', '');
  lines.push('The `State` property axis contains values that are not interaction states. These should be moved to separate axes in Figma.', '');

  const stateAxis = axes.find((a) => a.axis === 'State');
  if (stateAxis) {
    const breakpoints = stateAxis.values.filter((v) => NON_STATE_BREAKPOINTS.has(v));
    const inputTypes = stateAxis.values.filter((v) => NON_STATE_INPUT_TYPES.has(v));
    const typos = stateAxis.values.filter((v) => STATE_TYPOS[v]);
    const autoGen = stateAxis.values.filter((v) => isInconsistentStateName(v));

    if (breakpoints.length > 0) {
      lines.push(`**Breakpoint values mixed into State axis:** \`${breakpoints.join('`, `')}\``);
      lines.push('→ These should be the `Size` axis (Desktop/Tablet/Mobile), not State.', '');
    }
    if (inputTypes.length > 0) {
      lines.push(`**Input type values mixed into State axis:** \`${inputTypes.join('`, `')}\``);
      lines.push('→ These should be the `Style` axis (Checkbox/Radio), not State.', '');
    }
    if (typos.length > 0) {
      lines.push('**Typos / inconsistent naming in State axis:**', '');
      lines.push('| Found | Should Be |');
      lines.push('|-------|-----------|');
      for (const t of typos) {
        lines.push(`| \`${t}\` | \`${STATE_TYPOS[t]}\` |`);
      }
      lines.push('');
    }
    if (autoGen.length > 0) {
      lines.push(`**Auto-generated state names:** \`${autoGen.join('`, `')}\``);
      lines.push('→ Replace with descriptive names.', '');
    }
  }

  // Naming inconsistencies (auto-generated values in any axis)
  lines.push('', '## Auto-Generated Property Values', '');
  const issues: Array<{ component: string; axis: string; badValues: string[] }> = [];
  for (const c of components) {
    for (const [axis, values] of Object.entries(c.properties)) {
      const badVals = values.filter((v) => isInconsistentStateName(v));
      if (badVals.length > 0) issues.push({ component: c.name, axis, badValues: badVals });
    }
  }

  if (issues.length > 0) {
    lines.push('| Component | Axis | Bad Value(s) | Action |');
    lines.push('|-----------|------|-------------|--------|');
    for (const issue of issues) {
      lines.push(`| ${issue.component} | ${issue.axis} | \`${issue.badValues.join('`, `')}\` | Rename with descriptive value in Figma |`);
    }
  } else {
    lines.push('No auto-generated names detected. ✅');
  }

  // Consolidation opportunities (algorithmic)
  lines.push('', '## 💡 Consolidation Opportunities', '');
  lines.push('Detected algorithmically from shared axes, name stems, and duplicate frames.', '');

  const candidates = detectConsolidationCandidates(components);
  if (candidates.length > 0) {
    lines.push('| Component A | Component B | Reason |');
    lines.push('|-------------|-------------|--------|');
    for (const c of candidates) {
      lines.push(`| ${c.compA} | ${c.compB} | ${c.reason} |`);
    }
  } else {
    lines.push('No consolidation candidates detected.');
  }

  // Variant explosion
  lines.push('', '## 💥 Variant Count Overview (Top 20)', '');
  lines.push('| Component | Section | Variant Count | Axes |');
  lines.push('|-----------|---------|---------------|------|');
  const sortedByVariants = [...components].sort((a, b) => b.variantCount - a.variantCount);
  for (const c of sortedByVariants.slice(0, 20)) {
    const axeCount = Object.keys(c.properties).length;
    lines.push(`| ${c.name} | ${SECTION_LABELS[c.section]} | ${c.variantCount} | ${axeCount} |`);
  }

  lines.push('', '---', `*Generated by \`build-inventory.ts\`*`);
  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Doc 06: Dependency Graph
// ---------------------------------------------------------------------------

function doc06DependencyGraph(components: FigmaComponent[]): string {
  const lines: string[] = [
    '# 06 · Component Dependency Graph',
    '',
    '> Initial mappings inferred from component names and Figma section hierarchy. Refine as needed.',
    '',
    '## Full Hierarchy',
    '',
    '```mermaid',
    'graph TD',
  ];

  lines.push('  subgraph htmlElements ["HTML Elements"]');
  const htmlEls = [...new Set(components.map((c) => c.suggestedHtmlElement))];
  for (const el of htmlEls) {
    const id = el.replace(/[^a-zA-Z0-9]/g, '_');
    lines.push(`    ${id}["&lt;${el}&gt;"]`);
  }
  lines.push('  end');

  const atoms = components.filter((c) => c.section === 'atoms');
  lines.push('  subgraph atomsGroup ["Atoms"]');
  for (const c of atoms) {
    const id = c.name.replace(/[^a-zA-Z0-9]/g, '_');
    lines.push(`    ${id}["${c.name}"]`);
  }
  lines.push('  end');

  const molecules = components.filter((c) => c.section === 'molecules');
  lines.push('  subgraph moleculesGroup ["Molecules"]');
  for (const c of molecules) {
    const id = c.name.replace(/[^a-zA-Z0-9]/g, '_');
    lines.push(`    ${id}["${c.name}"]`);
  }
  lines.push('  end');

  const inputs = components.filter((c) => c.section === 'inputs');
  lines.push('  subgraph inputsGroup ["Inputs"]');
  for (const c of inputs) {
    const id = c.name.replace(/[^a-zA-Z0-9]/g, '_');
    lines.push(`    ${id}["${c.name}"]`);
  }
  lines.push('  end');

  lines.push('', '  %% HTML to Atom and Input connections');
  for (const c of [...atoms, ...inputs]) {
    const compId = c.name.replace(/[^a-zA-Z0-9]/g, '_');
    const htmlId = c.suggestedHtmlElement.replace(/[^a-zA-Z0-9]/g, '_');
    lines.push(`  ${htmlId} --> ${compId}`);
  }

  lines.push('', '  %% Atom/Input to Molecule connections');
  for (const [molName, deps] of Object.entries(DEPENDENCY_MAP)) {
    const mol = components.find((c) => c.name === molName);
    if (!mol || mol.section !== 'molecules') continue;
    const molId = molName.replace(/[^a-zA-Z0-9]/g, '_');
    for (const dep of deps) {
      const depId = dep.replace(/[^a-zA-Z0-9]/g, '_');
      lines.push(`  ${depId} --> ${molId}`);
    }
  }
  lines.push('```');

  lines.push('', '## Atoms with Internal Dependencies', '');
  lines.push('```mermaid', 'graph TD');
  lines.push('  subgraph atomDeps ["Atom Internal Dependencies"]');
  for (const [name, deps] of Object.entries(DEPENDENCY_MAP)) {
    const comp = components.find((c) => c.name === name && c.section === 'atoms');
    if (!comp || deps.length === 0) continue;
    const parentId = name.replace(/[^a-zA-Z0-9]/g, '_');
    for (const dep of deps) {
      const depId = dep.replace(/[^a-zA-Z0-9]/g, '_');
      lines.push(`    ${depId}["${dep}"] --> ${parentId}["${name}"]`);
    }
  }
  lines.push('  end', '```');

  lines.push('', '## Molecule → Atom Dependencies', '');
  lines.push('| Molecule | Depends On |');
  lines.push('|----------|------------|');
  for (const c of molecules.sort((a, b) => a.name.localeCompare(b.name))) {
    const deps = DEPENDENCY_MAP[c.name] ?? [];
    lines.push(`| ${c.name} | ${deps.length > 0 ? deps.join(', ') : '—'} |`);
  }

  lines.push('', '---', `*Generated by \`build-inventory.ts\`*`);
  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Doc 07: Priority Dashboard (with dependency weight)
// ---------------------------------------------------------------------------

interface PriorityScore {
  component: FigmaComponent;
  sectionScore: number;
  variantScore: number;
  stateScore: number;
  responsiveScore: number;
  depScore: number;
  total: number;
  recommendation: string;
}

function scorePriority(c: FigmaComponent, depWeight: Map<string, number>): PriorityScore {
  const sectionScore = c.section === 'atoms' ? 3 : c.section === 'inputs' ? 2 : c.section === 'molecules' ? 1 : 0;

  const stateValues = c.properties['State'] ?? c.properties['Property 1'] ?? [];
  const inconsistentCount = stateValues.filter((v) => isInconsistentStateName(v)).length;
  const variantScore = inconsistentCount === 0 ? 2 : Math.max(0, 2 - inconsistentCount);

  const hasDefaultStates =
    stateValues.some((v) => /default/i.test(v)) &&
    stateValues.some((v) => /hover/i.test(v)) &&
    stateValues.some((v) => /disabled?/i.test(v));
  const stateScore = hasDefaultStates ? 2 : stateValues.length > 0 ? 1 : 0;

  const responsiveScore = c.hasResponsive ? 1 : 0;

  // Dependency weight: how many other components depend on this one
  const dependents = depWeight.get(c.name) ?? 0;
  const depScore = dependents >= 3 ? 2 : dependents >= 1 ? 1 : 0;

  const total = sectionScore + variantScore + stateScore + responsiveScore + depScore;

  let recommendation: string;
  if (inconsistentCount > 0) {
    recommendation = '⚠️ Needs Figma cleanup (inconsistent state names)';
  } else if (total >= 7) {
    recommendation = '✅ Build first — high dependency weight';
  } else if (total >= 5) {
    recommendation = '✅ Ready to build';
  } else if (total >= 3) {
    recommendation = '🔄 Build with minor caveats';
  } else {
    recommendation = '⏳ Address coverage gaps first';
  }

  return { component: c, sectionScore, variantScore, stateScore, responsiveScore, depScore, total, recommendation };
}

interface CodeComponentScore {
  cc: CodeComponent;
  maxTotal: number;
  maxRecommendation: string;
  figmaFrameCount: number;
  hasCleanupNeeded: boolean;
  allDepCount: number;
}

function scoreCodeComponent(
  cc: CodeComponent,
  components: FigmaComponent[],
  depWeight: Map<string, number>
): CodeComponentScore {
  const sourceFrames = components.filter((c) => cc.figmaSources.includes(c.name));
  if (sourceFrames.length === 0) {
    return { cc, maxTotal: 0, maxRecommendation: '⏳ No Figma frames found', figmaFrameCount: 0, hasCleanupNeeded: false, allDepCount: 0 };
  }

  const frameScores = sourceFrames.map((c) => scorePriority(c, depWeight));
  const best = frameScores.reduce((a, b) => b.total > a.total ? b : a);

  // Aggregate dep count across all Figma sources
  const allDepCount = sourceFrames.reduce((sum, c) => sum + (depWeight.get(c.name) ?? 0), 0);
  const hasCleanupNeeded = frameScores.some((s) => s.recommendation.startsWith('⚠️'));

  let recommendation = best.recommendation;
  if (hasCleanupNeeded && !recommendation.startsWith('⚠️')) {
    recommendation = `${recommendation} (some frames need Figma cleanup)`;
  }

  return {
    cc,
    maxTotal: best.total,
    maxRecommendation: recommendation,
    figmaFrameCount: sourceFrames.length,
    hasCleanupNeeded,
    allDepCount,
  };
}

function doc07PriorityDashboard(components: FigmaComponent[], taxonomy: Taxonomy): string {
  const depWeight = buildDependencyWeight();
  const codeComponents = taxonomy.codeComponents;

  const lines: string[] = [
    '# 07 · Build Priority Dashboard',
    '',
    '> Scored by **code component** (not Figma frame). Multiple Figma frames may contribute to one code component.',
    '> Score = max across constituent Figma frames. **Scoring:** Section (atoms=3, inputs=2, molecules=1) + Variant quality (2) + State coverage (2) + Responsive (1) + Dependency weight (2). Max = 10.',
    '',
    '## By Code Component',
    '',
  ];

  const scores = codeComponents
    .map((cc) => scoreCodeComponent(cc, components, depWeight))
    .sort((a, b) => b.maxTotal - a.maxTotal || a.cc.name.localeCompare(b.cc.name));

  lines.push('| Code Component | Tier | Category | Figma Frames | Dep | **Score** | Recommendation |');
  lines.push('|----------------|------|----------|-------------|-----|-----------|----------------|');
  for (const s of scores) {
    const depLabel = s.allDepCount > 0 ? `${s.allDepCount}` : '0';
    const cleanup = s.hasCleanupNeeded ? ' ⚠️' : '';
    lines.push(
      `| \`${s.cc.name}\` | ${TIER_LABELS[s.cc.tier]} | ${CATEGORY_LABELS[s.cc.functionalCategory]} | ${s.figmaFrameCount}${cleanup} | ${depLabel} | **${s.maxTotal}** | ${s.maxRecommendation} |`
    );
  }

  // Also keep the full Figma-frame view for reference
  lines.push('', '## By Figma Frame (full detail)', '');
  lines.push('> The source data — one row per Figma component frame.', '');

  const frameScores = components
    .map((c) => scorePriority(c, depWeight))
    .sort((a, b) => b.total - a.total || a.component.name.localeCompare(b.component.name));

  lines.push('| Figma Frame | Code Component | Section | Sec | Var | State | Resp | Dep | **Total** | Recommendation |');
  lines.push('|-------------|----------------|---------|-----|-----|-------|------|-----|-----------|----------------|');
  for (const s of frameScores) {
    const depCount = depWeight.get(s.component.name) ?? 0;
    const depLabel = depCount > 0 ? `${s.depScore} (${depCount})` : '0';
    const codeName = taxonomy.codeComponents.find((cc) => cc.figmaSources.includes(s.component.name))?.name ?? '—';
    lines.push(
      `| ${s.component.name} | \`${codeName}\` | ${SECTION_LABELS[s.component.section]} | ${s.sectionScore} | ${s.variantScore} | ${s.stateScore} | ${s.responsiveScore} | ${depLabel} | **${s.total}** | ${s.recommendation} |`
    );
  }

  const ready = frameScores.filter((s) => s.recommendation.startsWith('✅')).length;
  const minor = frameScores.filter((s) => s.recommendation.startsWith('🔄')).length;
  const cleanup = frameScores.filter((s) => s.recommendation.startsWith('⚠️')).length;
  const deferred = frameScores.filter((s) => s.recommendation.startsWith('⏳')).length;

  lines.push('', '## Summary', '');
  lines.push('| Status | Count |', '|--------|-------|');
  lines.push(`| ✅ Ready / high priority | ${ready} |`);
  lines.push(`| 🔄 Build with minor caveats | ${minor} |`);
  lines.push(`| ⚠️ Needs Figma cleanup | ${cleanup} |`);
  lines.push(`| ⏳ Deferred | ${deferred} |`);

  lines.push('', '---', `*Generated by \`build-inventory.ts\`*`);
  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Doc 08: Functional Taxonomy
// ---------------------------------------------------------------------------

function doc08Taxonomy(components: FigmaComponent[], taxonomy: Taxonomy): string {
  const codeComponents = taxonomy.codeComponents;
  const primitives = codeComponents.filter((cc) => cc.tier === 'primitive');
  const compositions = codeComponents.filter((cc) => cc.tier === 'composition');
  const builderBlocks = codeComponents.filter((cc) => cc.tier === 'builder-block');

  const lines: string[] = [
    '# 08 · Functional Taxonomy',
    '',
    '> **Three-axis classification:** Atomic level (Figma) · Functional category (purpose) · Component tier (code architecture).',
    '',
    '## Component Tiers',
    '',
    '> The tier determines the file structure, Builder.io registration requirement, and how content authors interact with the component.',
    '',
    '| Tier | Description | Builder.io | File Structure |',
    '|------|-------------|------------|----------------|',
    '| **Primitive** | Standalone React component. No Builder.io dependency in `component.tsx`. | Optional `register.tsx` | `component.tsx`, `register.tsx`, `component.test.tsx`, `index.ts` |',
    '| **Composition** | Multi-primitive React component, React-first. May use `BuilderBlocks` for editable slots. | `register.tsx` recommended | Same as primitive |',
    '| **Builder Block** | Page-level composition primarily consumed via Builder.io. `BuilderBlocks` required for content areas. | `register.tsx` required | Same + default block values in `register.tsx` |',
    '',
  ];

  // Tier overview Mermaid
  lines.push('## Code Component Architecture', '');
  lines.push('```mermaid', 'graph TD');
  lines.push('  subgraph primitives ["Primitives (18)"]');
  for (const cc of primitives) {
    lines.push(`    ${cc.name}["${cc.name}"]`);
  }
  lines.push('  end');
  lines.push('  subgraph compositions ["Compositions (9)"]');
  for (const cc of compositions) {
    lines.push(`    ${cc.name}["${cc.name}"]`);
  }
  lines.push('  end');
  lines.push('  subgraph builderBlocks ["Builder Blocks (4)"]');
  for (const cc of builderBlocks) {
    lines.push(`    ${cc.name}["${cc.name}"]`);
  }
  lines.push('  end');
  lines.push('```');

  // Category overview
  lines.push('', '## Category Overview', '', '```mermaid', 'graph TD', '  DesignSystem["Logos Design System"]');
  for (const cat of taxonomy.categories) {
    const id = cat.id.replace(/-/g, '_');
    lines.push(`  DesignSystem --> ${id}["${cat.label}\\n(${cat.codeComponents.length} code / ${cat.components.length} Figma)"]`);
  }
  lines.push('```');

  lines.push('', '## Category Definitions', '');
  for (const cat of taxonomy.categories) {
    const catCodeComps = codeComponents.filter((cc) => cc.functionalCategory === cat.id);
    lines.push(`### ${cat.label}`, '');
    lines.push(`> ${cat.description}`, '');
    if (catCodeComps.length > 0) {
      lines.push('**Code components:**', '');
      lines.push('| Code Component | Tier | Figma Sources |');
      lines.push('|----------------|------|---------------|');
      for (const cc of catCodeComps) {
        lines.push(`| \`${cc.name}\` | ${TIER_LABELS[cc.tier]} | ${cc.figmaSources.join(', ')} |`);
      }
    }
    lines.push('');
  }

  // Triple-axis classification table
  lines.push('## Triple-Axis Classification', '');
  lines.push('Every Figma frame mapped to its atomic level, functional category, and code component tier.', '');
  lines.push('| Figma Frame | Atomic Level | Functional Category | Code Component | Tier |');
  lines.push('|-------------|-------------|---------------------|----------------|------|');
  for (const c of [...components].sort((a, b) => a.name.localeCompare(b.name))) {
    const cc = codeComponents.find((x) => x.figmaSources.includes(c.name));
    const codeName = cc ? `\`${cc.name}\`` : '—';
    const tier = cc ? TIER_LABELS[cc.tier] : '—';
    lines.push(`| ${c.name} | ${SECTION_LABELS[c.section]} | ${CATEGORY_LABELS[c.functionalCategory]} | ${codeName} | ${tier} |`);
  }

  // Proposed folder structure
  lines.push('', '## Proposed Code Folder Structure', '');
  lines.push('Follows the existing `commerce-components` convention: kebab-case directory per component, `component.tsx` / `register.tsx` / `component.test.tsx` / `index.ts`.', '');
  lines.push('```');
  for (const line of taxonomy.proposedFolderStructure) {
    lines.push(line);
  }
  lines.push('```');

  // "Other" reclassification
  lines.push('', '## Note on "Other" Figma Section', '');
  lines.push('The 6 components in Figma\'s "Other" section are reclassified as follows:', '');
  const others = components.filter((c) => c.section === 'other');
  lines.push('| Figma Frame | Functional Category | Code Component | Rationale |');
  lines.push('|-------------|---------------------|----------------|-----------|');
  const otherRationale: Record<string, string> = {
    'Badges and Tags': 'Standalone display atom',
    'Price and Label': 'Commerce display atom',
    'Sale Percentage': 'Badge variant for promotional pricing',
    'Image Ratios': 'Layout constraint — consider removing from component inventory',
    'Product Images': 'Commerce display atom',
    'List': 'Generic atom used inside content sections',
  };
  for (const c of others) {
    const cc = codeComponents.find((x) => x.figmaSources.includes(c.name));
    lines.push(`| ${c.name} | ${CATEGORY_LABELS[c.functionalCategory]} | ${cc ? `\`${cc.name}\`` : '—'} | ${otherRationale[c.name] ?? '—'} |`);
  }

  lines.push('', '---', `*Generated by \`build-inventory.ts\`*`);
  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Doc 09: Component Architecture
// ---------------------------------------------------------------------------

function doc09ComponentArchitecture(components: FigmaComponent[], taxonomy: Taxonomy): string {
  const codeComponents = taxonomy.codeComponents;
  const primitives = codeComponents.filter((cc) => cc.tier === 'primitive');
  const compositions = codeComponents.filter((cc) => cc.tier === 'composition');
  const builderBlocks = codeComponents.filter((cc) => cc.tier === 'builder-block');

  const lines: string[] = [
    '# 09 · Component Architecture',
    '',
    '> React-first component architecture: multiple Figma frames collapse into semantic code components with typed props.',
    '> Builder.io registration is always in a separate `register.tsx` file — never in `component.tsx`.',
    '',
  ];

  // ── Section A: Code component list ─────────────────────────────────────────
  lines.push('## A · Code Components', '');
  lines.push(`${codeComponents.length} code components derived from ${components.length} Figma frames.`, '');

  for (const [label, list] of [
    ['Primitives', primitives],
    ['Compositions', compositions],
    ['Builder Blocks', builderBlocks],
  ] as [string, CodeComponent[]][]) {
    lines.push(`### ${label} (${list.length})`, '');
    lines.push('| Component | Directory | Category | Figma Sources | HTML |');
    lines.push('|-----------|-----------|----------|---------------|------|');
    for (const cc of list) {
      lines.push(
        `| \`${cc.name}\` | \`${cc.directoryName}/\` | ${CATEGORY_LABELS[cc.functionalCategory]} | ${cc.figmaSources.join(', ')} | \`<${cc.htmlElement}>\` |`
      );
    }
    lines.push('');
  }

  // ── Section B: Prop API conventions ────────────────────────────────────────
  lines.push('## B · Prop API Conventions', '');
  lines.push('These conventions come from `CommerceComponents/.github/copilot-instructions.md` and `BuilderIoBestPractices.mdx`.', '');
  lines.push(`
### \`variant\` — Visual hierarchy
Describes **what the variant is**, never how it looks. No color words.

| Value | Meaning |
|-------|---------|
| \`primary\` | Highest visual prominence, main CTA |
| \`secondary\` | Supporting action |
| \`tertiary\` | Low-emphasis, ghost-style action |
| \`arrow-link\` | Inline navigational link with arrow |
| \`icon-only\` | No label, icon carries meaning |
| \`floating\` | FAB — fixed/absolute positioned |

Surface suffixes append to variant values when needed:
- \`primary-inverse\` — primary on a dark/inverted surface
- \`primary-brand\` — primary on the brand blue surface

Semantic variants for status-bearing components:
- \`success\`, \`warning\`, \`error\`, \`info\`

---

### \`scale\` — Size
Always a **separate prop** from \`variant\`. Never encode size in the variant name.

| Value | Token reference |
|-------|-----------------|
| \`sm\` | \`--cc-scale-sm\` |
| \`md\` | \`--cc-scale-md\` (default) |
| \`lg\` | \`--cc-scale-lg\` |

---

### \`state\` — Interaction state
Map Figma \`State=\` axis values to these prop values. States are typically internal (controlled via CSS) but exposed as a prop for Storybook testing.

\`default\` | \`hover\` | \`focus\` | \`active\` | \`disabled\` | \`error\` | \`success\` | \`filled\` | \`loading\`

---

### CSS class prefix
All components use the \`cc-\` prefix: \`cc-button\`, \`cc-input\`, \`cc-product-card\`.
`);

  // ── Section C: Figma axis to prop mapping table ─────────────────────────────
  lines.push('## C · Figma Axis → Code Prop Mapping', '');
  lines.push('How Figma property axes translate to React component props.', '');
  lines.push('| Figma Axis | Figma Values (examples) | Code Prop | Code Values |');
  lines.push('|------------|------------------------|-----------|-------------|');
  lines.push('| `Type` | `CTA (Default)`, `Secondary CTA` | `variant` | `primary`, `secondary` |');
  lines.push('| `Type` | `Solid`, `Outline`, `Ghost` | `variant` | `primary`, `secondary`, `tertiary` (semantic, not appearance) |');
  lines.push('| `Size` | `Large`, `Medium`, `Small` | `scale` | `lg`, `md`, `sm` |');
  lines.push('| `State` | `Default`, `Hover`, `Disabled` | `state` (or CSS) | `default`, `hover`, `disabled` |');
  lines.push('| `State` | `Error`, `Success` | `state` | `error`, `success` |');
  lines.push('| `Background` | `Light`, `Dark`, `Logos Blue` | `variant` suffix | `primary`, `primary-inverse`, `primary-brand` |');
  lines.push('| `Direction` | `Left`, `Right`, `Next`, `Previous` | `iconPosition` | `leading`, `trailing` |');
  lines.push('| `Style` | `Checkbox`, `Radio` | `type` | `checkbox`, `radio` |');
  lines.push('| `Responsive` | `Desktop`, `Tablet`, `Mobile` | CSS only | handled via CSS breakpoints, not a prop |');
  lines.push('');

  // ── Section D: Token naming rules ──────────────────────────────────────────
  lines.push('## D · Token Naming Rules', '');
  lines.push(`
### Token format
\`{tier}-{category}-{variant}-{property}\`

- **Primitive tier:** no prefix — raw values: \`logos-blue-500\`, \`spacing-4\`
- **Semantic tier:** category prefix — \`color-brand-primary\`, \`spacing-h-md\`, \`shadow-elevation-1\`
- **Component tier:** \`component-{name}-{property}\` — \`component-button-padding-horizontal\`
- **All kebab-case.** No camelCase.

### Examples

| Figma Variable | CSS Variable | DTCG Tier |
|----------------|-------------|-----------|
| \`Primary/Logos Blue\` | \`--cc-color-brand-primary\` | Semantic |
| \`Deep Colors/Green\` | \`--cc-color-feedback-success\` | Semantic |
| \`Spacing | Horizontal/MD\` | \`--cc-spacing-h-md\` | Semantic |
| \`Spacing | In Component/CTA Button | Horizontal\` | \`--cc-component-button-padding-horizontal\` | Component |
`);

  // ── Section E: Directory structure ─────────────────────────────────────────
  lines.push('## E · Directory Structure', '');
  lines.push('Each code component gets its own directory under `packages/commerce-components/src/components/`.', '');
  lines.push('```');
  lines.push('packages/commerce-components/src/components/');
  lines.push('  button/');
  lines.push('    component.tsx    # React component — zero Builder.io imports');
  lines.push('    register.tsx     # Builder.io registration, inputs, defaults');
  lines.push('    component.test.tsx');
  lines.push('    index.ts         # barrel: export { Button } from "./component"');
  lines.push('  input/');
  lines.push('    component.tsx');
  lines.push('    register.tsx');
  lines.push('    component.test.tsx');
  lines.push('    index.ts');
  lines.push('  # ... one directory per code component');
  lines.push('```');
  lines.push('');
  lines.push('> **Rule:** `component.tsx` must not import anything from `@builder.io/*`. Builder.io concerns live exclusively in `register.tsx`.');
  lines.push('');

  // ── Full mapping table ──────────────────────────────────────────────────────
  lines.push('## F · Full Figma → Code Mapping', '');
  lines.push('Every Figma frame and the code component it maps to.', '');
  lines.push('| Figma Frame | Code Component | Tier | CSS Class | Key Props |');
  lines.push('|-------------|----------------|------|-----------|-----------|');
  for (const c of [...components].sort((a, b) => a.name.localeCompare(b.name))) {
    const cc = codeComponents.find((x) => x.figmaSources.includes(c.name));
    if (!cc) {
      lines.push(`| ${c.name} | — | — | — | — |`);
      continue;
    }
    const cssClass = `cc-${cc.directoryName}`;
    const keyProps = cc.props.map((p) => `\`${p.name}\``).join(', ') || '—';
    lines.push(`| ${c.name} | \`${cc.name}\` | ${TIER_LABELS[cc.tier]} | \`${cssClass}\` | ${keyProps} |`);
  }

  lines.push('', '---', `*Generated by \`build-inventory.ts\`*`);
  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Doc 10: Figma Cleanup Checklist
// ---------------------------------------------------------------------------

function doc10FigmaCleanup(components: FigmaComponent[], gap: GapAnalysis, taxonomy: Taxonomy): string {
  const codeComponents = taxonomy.codeComponents;

  const lines: string[] = [
    '# 10 · Figma Cleanup Checklist',
    '',
    '> Actionable items to improve Figma consistency before building components in code.',
    '> Check items off as you address them and re-run `npm run build` to verify.',
    '',
  ];

  // 0. Figma frames to code component mapping
  lines.push('## 0. Figma → Code Component Consolidation', '');
  lines.push('The following table shows which Figma frames will be collapsed into a single React component. Designers can optionally restructure Figma to reflect this hierarchy, but it is not required.', '');
  lines.push('| Code Component | Tier | Figma Frames |');
  lines.push('|----------------|------|--------------|');
  for (const cc of codeComponents) {
    lines.push(`| \`${cc.name}\` | ${TIER_LABELS[cc.tier]} | ${cc.figmaSources.join(', ')} |`);
  }
  lines.push('');
  const unmappedFrames = components.filter((c) => !codeComponents.some((cc) => cc.figmaSources.includes(c.name)));
  if (unmappedFrames.length > 0) {
    lines.push('### Unmapped Figma frames', '');
    lines.push('These frames are not yet assigned to a code component — review and assign:', '');
    for (const c of unmappedFrames) {
      lines.push(`- [ ] **${c.name}** (${CATEGORY_LABELS[c.functionalCategory]})`);
    }
    lines.push('');
  }

  // 1. Rename auto-generated state values
  lines.push('## 1. Rename Auto-Generated Property Values', '');
  lines.push('These components have Figma auto-names (`State2`, `Variant4`, etc.) that make it impossible to know what state is being represented.', '');

  const autoGenIssues: Array<{ component: string; axis: string; bad: string }> = [];
  for (const c of components) {
    for (const [axis, values] of Object.entries(c.properties)) {
      for (const v of values) {
        if (isInconsistentStateName(v)) {
          autoGenIssues.push({ component: c.name, axis, bad: v });
        }
      }
    }
  }
  for (const issue of autoGenIssues) {
    lines.push(`- [ ] **${issue.component}** — rename \`${issue.axis}=${issue.bad}\` to a descriptive value`);
  }

  // 2. Fix state axis pollution
  lines.push('', '## 2. Fix State Axis Pollution', '');
  lines.push('Values incorrectly placed in the `State` axis.', '');

  for (const c of components) {
    const stateValues = c.properties['State'] ?? [];
    const breakpointsInState = stateValues.filter((v) => NON_STATE_BREAKPOINTS.has(v));
    const inputTypesInState = stateValues.filter((v) => NON_STATE_INPUT_TYPES.has(v));
    const typosInState = stateValues.filter((v) => STATE_TYPOS[v]);

    for (const v of breakpointsInState) {
      lines.push(`- [ ] **${c.name}** — move \`State=${v}\` to the \`Size\` axis`);
    }
    for (const v of inputTypesInState) {
      lines.push(`- [ ] **${c.name}** — move \`State=${v}\` to the \`Style\` axis`);
    }
    for (const v of typosInState) {
      lines.push(`- [ ] **${c.name}** — rename \`State=${v}\` to \`State=${STATE_TYPOS[v]}\``);
    }
  }

  // 3. Deduplicate frames
  lines.push('', '## 3. Deduplicate Component Frames', '');
  lines.push('Components with duplicate names that appear twice in Figma:', '');
  const nameCounts = new Map<string, string[]>();
  for (const c of components) {
    if (!nameCounts.has(c.name)) nameCounts.set(c.name, []);
    nameCounts.get(c.name)!.push(c.figmaId);
  }
  let hasDuplicates = false;
  for (const [name, ids] of nameCounts.entries()) {
    if (ids.length > 1) {
      hasDuplicates = true;
      lines.push(`- [ ] **${name}** — appears ${ids.length} times (IDs: ${ids.join(', ')}) — delete or rename the duplicate`);
    }
  }
  if (!hasDuplicates) lines.push('No duplicates found. ✅');

  // 4. Add missing critical states
  lines.push('', '## 4. Add Missing Critical States', '');
  lines.push('Components missing Hover, Focus, or Disabled states (minimum viable interactive states).', '');

  const missStates = ['Hover', 'Disabled'];
  for (const c of components) {
    const stateValues = (c.properties['State'] ?? []).map((v) => v.toLowerCase());
    if (stateValues.length === 0) continue;
    const missing = missStates.filter((s) => !stateValues.includes(s.toLowerCase()));
    if (missing.length > 0) {
      lines.push(`- [ ] **${c.name}** — add \`${missing.join(', ')}\` state variant(s)`);
    }
  }

  // 5. Reclassify "Other" section
  lines.push('', '## 5. Reclassify "Other" Section Components', '');
  lines.push('Move components out of the catch-all "Other" Figma section into their proper atomic sections.', '');
  const others = components.filter((c) => c.section === 'other');
  const reclassify: Record<string, string> = {
    'Badges and Tags': 'Atoms',
    'Price and Label': 'Atoms',
    'Sale Percentage': 'Atoms',
    'List': 'Atoms',
    'Product Images': 'Atoms',
    'Image Ratios': 'Consider removing — this is a layout constraint, not a component',
  };
  for (const c of others) {
    lines.push(`- [ ] **${c.name}** → move to **${reclassify[c.name] ?? 'Atoms'}** section`);
  }

  // 6. Standardize responsive coverage
  lines.push('', '## 6. Add Responsive Variants', '');
  lines.push('Key molecules/atoms that should have Desktop + Tablet + Mobile variants but currently do not.', '');

  const highPriorityForResponsive = ['Button', 'Text Input (single line)', 'Dropdown', 'Search Field', 'Toast Bar', 'Carousel Product', 'Product Content'];
  for (const name of highPriorityForResponsive) {
    const comp = components.find((c) => c.name === name);
    if (comp && !comp.hasResponsive) {
      lines.push(`- [ ] **${name}** — add Desktop, Tablet, Mobile size variants`);
    }
  }

  // 7. Token implementation gaps
  lines.push('', '## 7. Implement Missing Tokens in Code', '');
  lines.push('Figma variables that have no matching token in `commerce-theme`.', '');

  lines.push('', '**Colors (in Figma, not in code):**');
  for (const e of gap.colors.figmaOnly) {
    lines.push(`- [ ] Add \`${e.figmaKey}\` (\`${e.figmaValue}\`) to \`commerce-theme/src/colors.ts\``);
  }

  lines.push('', '**Spacing (in Figma, not in code):**');
  for (const e of gap.spacing.figmaOnly) {
    lines.push(`- [ ] Add \`${e.figmaKey}\` (\`${e.figmaValue}\`) to \`commerce-theme/src/spacing.ts\``);
  }

  lines.push('', '**Shadows (in Figma, not in code):**');
  for (const e of gap.shadows.figmaOnly) {
    lines.push(`- [ ] Add \`${e.figmaKey}\` to \`commerce-theme/src/shadows.ts\``);
  }

  // 8. Review code-only tokens
  lines.push('', '## 8. Audit Code-Only Tokens', '');
  lines.push('Tokens that exist in `commerce-theme` but have no Figma variable. These are either orphaned (remove) or missing from Figma (add variable).', '');

  if (gap.colors.codeOnly.length > 0) {
    lines.push('', '**Code-only colors:**');
    for (const e of gap.colors.codeOnly) {
      lines.push(`- [ ] \`${e.codeKey}\` (\`${e.codeValue}\`) — add to Figma or remove from \`colors.ts\``);
    }
  }

  if (gap.spacing.codeOnly.length > 0) {
    lines.push('', '**Code-only spacing:**');
    for (const e of gap.spacing.codeOnly) {
      lines.push(`- [ ] \`${e.codeKey}\` (\`${e.codeValue}\`) — add to Figma or remove from \`spacing.ts\``);
    }
  }

  lines.push('', '---', `*Generated by \`build-inventory.ts\`*`);
  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// README (updated with new docs)
// ---------------------------------------------------------------------------

// ─── Doc 11: Design Token Migration Guide ────────────────────────────────────

interface BrandStylesAuditFile {
  summary: {
    counts: Record<MigrationStatus, number>;
    byPriority: Record<MigrationPriority, number>;
    total: number;
  };
  bySummaryType: Record<string, { counts: Record<MigrationStatus, number>; total: number }>;
  items: TokenMigrationItem[];
}

function statusBadge(status: MigrationStatus): string {
  switch (status) {
    case 'variable': return '✅ variable';
    case 'local-style-only': return '🔴 local style';
    case 'duplicate': return '🟡 duplicate';
    case 'missing': return '⬜ missing';
  }
}

function priorityBadge(priority: MigrationPriority): string {
  switch (priority) {
    case 'critical': return '🚨 critical';
    case 'high': return '🔶 high';
    case 'medium': return '🔷 medium';
    case 'low': return '⚪ low';
  }
}

function doc11DesignTokenMigration(audit: BrandStylesAuditFile): string {
  const items = audit.items;
  const needsMigration = items.filter(i => i.status === 'local-style-only');
  const duplicates = items.filter(i => i.status === 'duplicate');
  const alreadyVariables = items.filter(i => i.status === 'variable');

  // Group local-style-only items by type
  const colorItems = needsMigration.filter(i => i.type === 'color');
  const shadowItems = needsMigration.filter(i => i.type === 'shadow');
  const gradientItems = needsMigration.filter(i => i.type === 'gradient');
  const typographyItems = needsMigration.filter(i => i.type === 'typography');

  const colorDupes = duplicates.filter(i => i.type === 'color');
  const typographyDupes = duplicates.filter(i => i.type === 'typography');

  // Build color migration rows grouped by sub-group
  function colorRows(colorList: TokenMigrationItem[], showSwatch = true): string {
    return colorList.map(item => {
      const swatch = showSwatch ? colorSwatch(item.extractedValue) : '';
      const value = item.extractedValue ? `\`${item.extractedValue}\`` : '—';
      return `| ${item.styleName} | ${swatch}${value} | ${priorityBadge(item.priority)} | ${item.notes || '—'} |`;
    }).join('\n');
  }

  // Build the recommended variable naming for new colors
  function suggestVariableName(styleName: string): string {
    const map: Record<string, string> = {
      'Secondary/Deep Blue 3': 'Secondary/Deep Blue 3',
      'Secondary/Light Blue 0': 'Secondary/Light Blue 0',
      'Deep Colors/Deep Orange': 'Deep Colors/Deep Orange',
      'Deep Colors/Deep Purple': 'Deep Colors/Deep Purple',
      'Bright Colors/Alt Orange': 'Bright Colors/Alt Orange',
      'Bright Colors/Alt Purple': 'Bright Colors/Alt Purple',
      'Bright Colors/Bright Green': 'Bright Colors/Bright Green',
      'Neutral/Black': 'Neutral/Black',
      'Core Swatches/Dark Blue': 'Core Swatches/Dark Blue',
      'Core Swatches/Logos Top Blue': 'Core Swatches/Logos Top Blue',
      'Logos Swatches/Faithlife Blue': 'Logos Swatches/Faithlife Blue',
      'Logos Swatches/Light Blue': 'Logos Swatches/Light Blue',
      'Logos Swatches/Faithlife Green': 'Logos Swatches/Faithlife Green',
      'Logos Swatches/Red': 'Logos Swatches/Red',
    };
    return map[styleName] ?? styleName;
  }

  // Split color items into sub-groups
  const primaryMissing = colorItems.filter(i => i.group === 'Primary' || i.group === 'Secondary');
  const paletteMissing = colorItems.filter(i => i.group === 'Deep Colors' || i.group === 'Bright Colors' || i.group === 'Neutral');
  const legacyMissing = colorItems.filter(i => i.group === 'Core Swatches' || i.group === 'Logos Swatches');
  const verbumMissing = colorItems.filter(i => i.group === 'Verbum');

  return `# 11 — Design Token Migration Guide

> **Audience:** Design team (Figma).
> **Purpose:** This document identifies every value in the Logos Brand Styles file that exists as a **local style** rather than a **Figma variable**. Local styles cannot be exported as W3C Design Tokens — they are invisible to the token pipeline. Each item below is an action for the design team to complete before it will appear in generated documentation and CSS.

---

## A. The Problem: Local Styles vs. Variables

Figma has two systems for reusable values:

| System | Exportable as DTCG token? | Supports modes/themes? | Status |
|---|---|---|---|
| **Figma Variables** (new) | ✅ Yes | ✅ Yes | Path forward |
| **Figma Local Styles** (legacy) | ❌ No | ❌ No | Needs migration |

When the MCP tool \`get_variable_defs\` is called on the Brand Styles file, it returns only the values that are **Figma Variables** — roughly 8 values shared from the Brand Components library. Everything else (colors, shadows, gradients, typography) is defined as a **local style** and is invisible to the export pipeline.

\`\`\`mermaid
graph LR
  subgraph brandComponents ["Brand Components File ✅"]
    vars["Figma Variables\\n(~101 tokens)"]
    vars -->|"get_variable_defs"| pipeline["Inventory Pipeline"]
  end
  subgraph brandStyles ["Brand Styles File ⚠️"]
    localStyles["Local Styles\\n(${needsMigration.length} items need migration)"]
    fewVars["Shared Variables\\n(${alreadyVariables.length} tokens)"]
    localStyles -.->|"NOT exportable"| gap["Design Token Gap"]
    fewVars -->|"get_variable_defs"| pipeline
  end
  pipeline --> docs["Generated Docs & CSS Variables"]
  gap --> migration["This Migration Guide"]
\`\`\`

---

## B. Migration Summary

| Metric | Count |
|---|---|
| Total items audited | **${items.length}** |
| ✅ Already a Figma variable (no action needed) | **${alreadyVariables.length}** |
| 🔴 Local style only — **needs migration to variable** | **${needsMigration.length}** |
| 🟡 Duplicate — same value exists as variable under different name | **${duplicates.length}** |

### By Type

| Type | Local Style Only | Duplicates | Variables |
|---|---|---|---|
| Colors | ${colorItems.length} | ${colorDupes.length} | ${alreadyVariables.filter(i=>i.type==='color').length} |
| Shadows | ${shadowItems.length} | 0 | ${alreadyVariables.filter(i=>i.type==='shadow').length} |
| Gradients | ${gradientItems.length} | 0 | 0 |
| Typography | ${typographyItems.length} | ${typographyDupes.length} | ${alreadyVariables.filter(i=>i.type==='typography').length} |

### By Priority (items needing migration only)

| Priority | Count | What it means |
|---|---|---|
| 🚨 Critical | ${needsMigration.filter(i=>i.priority==='critical').length} | Used by components — blocking design-to-code connection |
| 🔶 High | ${needsMigration.filter(i=>i.priority==='high').length} | Core palette — high visibility, used in many places |
| 🔷 Medium | ${needsMigration.filter(i=>i.priority==='medium').length} | Secondary colors, extended shadow scale |
| ⚪ Low | ${needsMigration.filter(i=>i.priority==='low').length} | Sub-brand (Verbum), gradients, legacy typography variants |

---

## C. Migration Checklist by Type

### C1. Colors — Needs Migration (${colorItems.length} items)

#### Primary & Secondary Palette Gaps (${primaryMissing.length} items)

These are the most critical — they are part of the core color system but not yet variables.

| Style Name | Value | Priority | Notes |
|---|---|---|---|
${colorRows(primaryMissing)}

#### Deep & Bright Colors + Neutral Gaps (${paletteMissing.length} items)

| Style Name | Value | Priority | Notes |
|---|---|---|---|
${colorRows(paletteMissing)}

#### Legacy Swatch Groups (${legacyMissing.length} items)

These are legacy groups (Core Swatches, Logos Swatches) that predate the current variable structure. Some values are unique (need new variables); others are duplicates of existing values under different names.

| Style Name | Value | Priority | Notes |
|---|---|---|---|
${colorRows(legacyMissing)}

#### Verbum Sub-Brand Colors (${verbumMissing.length} items)

Sub-brand colors — only needed if Verbum brand is actively maintained in this file.

| Style Name | Value | Priority | Notes |
|---|---|---|---|
${colorRows(verbumMissing)}

### C2. Shadows — Needs Migration (${shadowItems.length} items)

Currently only **Shadows/4dp** and **Shadows/6dp** are Figma variables. The full elevation scale and the entire "Shadows - L9" alternate set need to be converted.

| Style Name | Priority | Notes |
|---|---|---|
${shadowItems.map(i => `| ${i.styleName} | ${priorityBadge(i.priority)} | ${i.notes || 'Needs variable definition'} |`).join('\n')}

**Recommended approach:** Create a \`Shadows\` variable collection with elevation levels 1dp–24dp. The L9 variant set can be a second collection or a mode within the same collection (decision for design team).

### C3. Gradients — Needs Migration (${gradientItems.length} items)

No gradient variables exist today. Figma does not natively support gradient-type variables in the same way as colors, but the approach is to either:
- Use **string variables** with CSS gradient notation, or
- Document gradient tokens as comments/annotations and map them manually in Style Dictionary

| Style Name | Value | Priority | Notes |
|---|---|---|---|
${gradientItems.map(i => `| ${i.styleName} | \`${i.extractedValue ?? '—'}\` | ${priorityBadge(i.priority)} | ${i.notes} |`).join('\n')}

### C4. Typography — Needs Migration (${typographyItems.length} items)

The current variable set covers H1–H6, Body, UI sizes, and Special Headings. Missing are:

- **2023/Headings/\*** — updated type scale from 2023, should replace or be reconciled with the legacy \`Headings/*\` local styles
- **Content responsive variants** (H1–H4 at Desktop/Tablet/Mobile) — no variable-backed responsive typography
- **Special/H\* responsive variants** — no variable counterpart

| Style Name | Priority | Notes |
|---|---|---|
${typographyItems.map(i => `| ${i.styleName} | ${priorityBadge(i.priority)} | ${i.notes} |`).join('\n')}

---

## D. Duplicate Consolidation (${duplicates.length} items)

These local styles have the **same value** as an existing Figma variable under a different name. The local style should be deleted and any usages should reference the existing variable directly.

### Color Duplicates (${colorDupes.length} items)

| Local Style | Existing Variable | Value |
|---|---|---|
${colorDupes.map(i => {
  const swatch = colorSwatch(i.extractedValue);
  const val = i.extractedValue ? `${swatch}\`${i.extractedValue}\`` : '—';
  return `| ${i.styleName} | ${i.existingVariableKey ?? '—'} | ${val} |`;
}).join('\n')}

### Typography Duplicates (${typographyDupes.length} items)

These local text styles have a variable counterpart — the local style should link to the variable rather than defining its own values.

| Local Style | Variable Counterpart | Action |
|---|---|---|
${typographyDupes.map(i => `| ${i.styleName} | ${i.existingVariableKey ?? '—'} | Link local style to variable |`).join('\n')}

---

## E. Recommended Variable Structure

### Color Variable Collection

Create or extend the **"Colors"** variable collection with these groups:

\`\`\`
Colors/
  Primary/
    Logos Blue          #1E6AFE  ✅ exists
    Subscription Blue   #00042F  ✅ exists
    Deep Blue           #030B60  ✅ exists
  Secondary/
    Alt Blue            #4885FE  ✅ exists
    Deep Blue 2         #040F8B  ✅ exists
    Deep Blue 3         #3640B8  🔴 ADD
    Light Blue 0        #9BCDFF  🔴 ADD
    Light Blue 1        #C1E4FF  ✅ exists
    Light Blue 2        #E9F5FF  ✅ exists
    Light Blue 3        #F5FBFF  ✅ exists
    Very Deep Gray      #303030  ✅ exists
    White               #FFFFFF  ✅ exists
  Neutral/
    Gray 1              #F5F5F5  🔴 ADD (consolidate from Core Swatches/Gray 1)
    Gray 2              #EBEBEB  🔴 ADD
    Gray 3              #DBDBDB  🔴 ADD
    Gray 4              #C7C7C7  🔴 ADD
    Deep Gray           #303030  🔴 ADD (= Very Deep Gray — confirm & deduplicate)
    Black               #000000  🔴 ADD
  Deep Colors/
    Yellow              #DBA910  ✅ exists
    Red                 #CC3333  ✅ exists
    Green               #5BA224  ✅ exists
    Deep Orange         #AD4100  🔴 ADD
    Deep Purple         #502D4C  🔴 ADD
  Bright Colors/
    Bright Yellow       #FFF369  ✅ exists
    Bright Red          #FF6D6D  ✅ exists
    Bright Green        #54EB54  🔴 ADD
    Alt Orange          #D87C44  🔴 ADD
    Alt Purple          #A4619C  🔴 ADD
\`\`\`

> **Note on duplicate groups:** "Core Swatches" and "Logos Swatches" are legacy groups — their unique values (Dark Blue, Logos Top Blue, Faithlife Blue, etc.) should be moved into the appropriate Primary/Secondary/Neutral groups above. The duplicate entries should be deleted once migrated.

### Shadow Variable Collection

Create a **"Shadows"** variable collection:

\`\`\`
Shadows/
  1dp    🔴 ADD
  2dp    🔴 ADD
  3dp    🔴 ADD
  4dp    ✅ exists
  6dp    ✅ exists
  8dp    🔴 ADD
  9dp    🔴 ADD
  12dp   🔴 ADD
  16dp   🔴 ADD
  24dp   🔴 ADD
Shadows - L9/  (or as a Mode within Shadows collection)
  1dp–24dp   🔴 ADD all 10 values
Product Shadows/
  Small    ✅ exists
  Medium   🔴 ADD
  Large    ✅ exists
\`\`\`

### Gradient Variable Collection (new)

\`\`\`
Gradients/
  One     🔴 ADD  linear-gradient(90deg, #F6FCFF, #FFFFFF)
  Two     🔴 ADD  linear-gradient(90deg, #E7F5FF, #F5FBFF)
  Three   🔴 ADD  linear-gradient(90deg, #C1E4FF, #E9F5FF)
  Four    🔴 ADD  linear-gradient(-90deg, #C1E4FF, #ACD7FF)
\`\`\`

> ⚠️ Figma variables do not yet have a native "gradient" type. Options:
> 1. Store as a **string variable** with the CSS value
> 2. Store the constituent stop colors as separate color variables and compose in code
> 3. Document as a Figma annotation — the token pipeline will pick them up once Figma supports gradient variables

### Typography

The current variable set in Brand Styles (via the Typography variable collection) covers H1–H6, Body sizes, and Special Headings. To complete coverage:

1. **Reconcile 2023/Headings/* with Headings/*** — Determine which is canonical and update variable values to match
2. **Add responsive scale** — Add variables for Content/H1-H4 at Desktop/Tablet/Mobile breakpoints (or implement via CSS \`clamp()\` in code, referencing existing heading variables)
3. **Add Special Headings/* responsive variants** — Add Special/H1-H2 Desktop and Mobile+Tablet variants

### Naming Conventions for New Variables

Follow the existing convention in Brand Components: \`Group/Subgroup/Name\`

- Group: \`Primary\`, \`Secondary\`, \`Neutral\`, \`Deep Colors\`, \`Bright Colors\`, \`Shadows\`, \`Gradients\`
- Use Title Case for group names
- Sub-group names in same style as existing tokens (e.g. \`Light Blue 1\`, \`Gray 1\`)
- Avoid encoding appearance (e.g. "Dark" in "Dark Gray") when a semantic name works; if you must use a descriptive name, match the existing scale naming

---

## F. Quick Action Checklist for Design Team

\`\`\`
[ ] Add Secondary/Deep Blue 3 (#3640B8) as a color variable
[ ] Add Secondary/Light Blue 0 (#9BCDFF) as a color variable
[ ] Add Deep Colors/Deep Orange (#AD4100) as a color variable
[ ] Add Deep Colors/Deep Purple (#502D4C) as a color variable
[ ] Add Bright Colors/Bright Green (#54EB54) as a color variable
[ ] Add Bright Colors/Alt Orange (#D87C44) as a color variable
[ ] Add Bright Colors/Alt Purple (#A4619C) as a color variable
[ ] Add Neutral/Gray 1–4 as color variables (consolidating from Core Swatches)
[ ] Add Neutral/Black (#000000) as a color variable
[ ] Add Shadows/1dp, 2dp, 3dp, 8dp, 9dp, 12dp, 16dp, 24dp as shadow variables
[ ] Add Product Shadows/Medium as a shadow variable
[ ] Add all 10 Shadows - L9/* as shadow variables (or as a shadow collection Mode)
[ ] Add Gradient/One–Four as gradient variables (string type or component stops)
[ ] Reconcile 2023/Headings/* with Headings/* typography variables
[ ] Delete duplicate local styles that reference existing variables (${colorDupes.length} color, ${typographyDupes.length} typography)
[ ] Review Core Swatches/Logos Blue (#005EC3) — different from Primary/Logos Blue (#1E6AFE), confirm which is correct
[ ] Decide Verbum sub-brand scope — if active, add ${verbumMissing.length} Verbum variables
\`\`\`
`;
}

function readme(components: FigmaComponent[], tokens: TokenCategory, gap: GapAnalysis, taxonomy: Taxonomy): string {
  const totalVariants = components.reduce((s, c) => s + c.variantCount, 0);
  const responsiveCount = components.filter((c) => c.hasResponsive).length;
  const codeComponents = taxonomy.codeComponents;
  const primitives = codeComponents.filter((cc) => cc.tier === 'primitive').length;
  const compositions = codeComponents.filter((cc) => cc.tier === 'composition').length;
  const builderBlocks = codeComponents.filter((cc) => cc.tier === 'builder-block').length;
  const catCounts = Object.entries(CATEGORY_LABELS)
    .map(([id, label]) => {
      const figmaCount = components.filter((c) => c.functionalCategory === id).length;
      const codeCount = codeComponents.filter((cc) => cc.functionalCategory === id).length;
      return `| ${label} | ${figmaCount} | ${codeCount} |`;
    })
    .join('\n');

  return `# Design System Inventory

> Logos Brand Components — generated from Figma MCP data.
> **Re-generate:** update \`raw/\` files then run \`npm run build\` in this directory.

## Stats

| | Count |
|--|-------|
| Figma component frames | ${components.length} |
| Code components | ${codeComponents.length} |
| Total Figma variants | ${totalVariants} |
| Responsive Figma frames | ${responsiveCount} |
| Figma color tokens | ${tokens.colors.length} |
| Colors matched in \`commerce-theme\` | ${gap.colors.matched.length} |
| Colors Figma-only (need code impl) | ${gap.colors.figmaOnly.length} |
| Colors code-only (orphaned) | ${gap.colors.codeOnly.length} |

## Code Component Architecture

| Tier | Count | Description |
|------|-------|-------------|
| Primitives | ${primitives} | Standalone React components |
| Compositions | ${compositions} | Multi-primitive compositions |
| Builder Blocks | ${builderBlocks} | Page-level Builder.io blocks |

## By Functional Category

| Category | Figma Frames | Code Components |
|----------|-------------|-----------------|
${catCounts}

## Documents

| # | Document | Description |
|---|----------|-------------|
| 01 | [Token Map](./01-token-map.md) | All Figma variables with DTCG tiers, swatches, and commerce-theme match status |
| 02 | [Component Inventory](./02-component-inventory.md) | All ${components.length} Figma frames with functional category, variants, axes, and HTML mappings |
| 03 | [State Completeness Matrix](./03-state-matrix.md) | Cross-component interaction state coverage |
| 04 | [Responsive Catalog](./04-responsive-catalog.md) | Figma frames grouped by responsive coverage |
| 05 | [Variant Analysis](./05-variant-analysis.md) | State axis quality, naming consistency, consolidation opportunities |
| 06 | [Dependency Graph](./06-dependency-graph.md) | HTML → Atom → Molecule relationships (Mermaid) |
| 07 | [Priority Dashboard](./07-priority-dashboard.md) | Build order scored by code component (${codeComponents.length} rows) with full Figma-frame detail |
| 08 | [Functional Taxonomy](./08-taxonomy.md) | Three-axis classification (atomic · category · tier), Mermaid diagram, folder structure |
| 09 | [Component Architecture](./09-component-architecture.md) | React-first component list, prop API conventions, Figma axis → prop mapping, directory structure |
| 10 | [Figma Cleanup Checklist](./10-figma-cleanup.md) | Figma → code consolidation map + actionable cleanup items |
| 11 | [Design Token Migration Guide](./11-design-token-migration.md) | Brand Styles audit — which local styles need to become Figma variables |

## Data Files

| File | Description |
|------|-------------|
| \`data/tokens.json\` | All Figma variables by category (incl. fontSizes) |
| \`data/components.json\` | All ${components.length} Figma frames with functionalCategory and proposedCodeName |
| \`data/code-components.json\` | ${codeComponents.length} code components with tier, props, and Figma source mapping |
| \`data/variant-axes.json\` | Deduplicated property axes across all Figma frames |
| \`data/taxonomy.json\` | Category definitions, code components, and proposed folder structure |
| \`data/gap-analysis.json\` | Figma vs. commerce-theme token comparison |
| \`data/brand-styles-audit.json\` | Brand Styles local styles vs. variables audit |
| \`data/dtcg/primitives.json\` | Tier 1 DTCG tokens (raw values) |
| \`data/dtcg/semantic.json\` | Tier 2 DTCG tokens (intent-based aliases) |
| \`data/dtcg/component.json\` | Tier 3 DTCG tokens (component-scoped) |

## Pipeline

\`\`\`
raw/figma-metadata.xml                 ─┐
raw/figma-variables.json               ─┤─► parse-figma.ts ──► data/*.json + code-components.json
                                        │
commerce-theme/src/*.ts                ─┤─► gap-analysis.ts + map-dtcg.ts ──► data/*.json
raw/figma-brand-styles-extracted.json  ─┘─► audit-brand-styles.ts ──► brand-styles-audit.json
                                            generate-docs.ts ──► docs/*.md (11 docs + README)
\`\`\`
`;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

export async function generateDocs() {
  console.log('\n=== generate-docs: generating markdown documents ===');

  const components: FigmaComponent[] = readJson('components.json');
  const axes: VariantAxis[] = readJson('variant-axes.json');
  const tokens: TokenCategory = readJson('tokens.json');
  const gap: GapAnalysis = readJson('gap-analysis.json');
  const taxonomy: Taxonomy = readJson('taxonomy.json');

  const docsDir = join(ROOT, 'docs');

  writeDoc(join(docsDir, '01-token-map.md'), doc01TokenMap(tokens, gap));
  writeDoc(join(docsDir, '02-component-inventory.md'), doc02ComponentInventory(components));
  writeDoc(join(docsDir, '03-state-matrix.md'), doc03StateMatrix(components));
  writeDoc(join(docsDir, '04-responsive-catalog.md'), doc04ResponsiveCatalog(components));
  writeDoc(join(docsDir, '05-variant-analysis.md'), doc05VariantAnalysis(components, axes));
  writeDoc(join(docsDir, '06-dependency-graph.md'), doc06DependencyGraph(components));
  writeDoc(join(docsDir, '07-priority-dashboard.md'), doc07PriorityDashboard(components, taxonomy));
  writeDoc(join(docsDir, '08-taxonomy.md'), doc08Taxonomy(components, taxonomy));
  writeDoc(join(docsDir, '09-component-architecture.md'), doc09ComponentArchitecture(components, taxonomy));
  writeDoc(join(docsDir, '10-figma-cleanup.md'), doc10FigmaCleanup(components, gap, taxonomy));

  const auditPath = join(ROOT, 'data', 'brand-styles-audit.json');
  if (existsSync(auditPath)) {
    const audit = JSON.parse(readFileSync(auditPath, 'utf-8')) as BrandStylesAuditFile;
    writeDoc(join(docsDir, '11-design-token-migration.md'), doc11DesignTokenMigration(audit));
    console.log(`  doc 11 written (brand-styles audit found)`);
  }

  writeDoc(join(docsDir, 'README.md'), readme(components, tokens, gap, taxonomy));

  console.log(`  documents written to ./docs/`);
}

const isMain = process.argv[1]?.endsWith('generate-docs.ts') || process.argv[1]?.endsWith('generate-docs.js');
if (isMain) generateDocs().catch((e) => { console.error(e); process.exit(1); });
